umijs/umi-next

.github/workflows/rebase.yml
=> chore: rebase ci

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/rfc_cn.md
=> chore: github issues template code style

.circleci/config.yml
- In a CI environment, using yarn command
=> chore(ci): using Yarn command

packages/core/src/Service/Service.test.ts, packages/core/src/Service/Service.ts
=> test(core): Service test

.github/commit-convention.md, tsconfig.json
=> chore: code style

docs/packages/server.md, packages/preset-built-in/src/index.test.ts, packages/preset-built-in/src/plugins/commands/dev/dev.ts, packages/server/package.json, packages/server/src/Server/Server.test.ts, packages/server/src/Server/Server.ts
=> feat: dev proxy middleware

packages/preset-built-in/src/plugins/commands/build/build.ts, packages/types/index.d.ts
=> fix: config types

docs/packages/bundler-webpack.md, packages/types/index.d.ts
=> fix: types

docs/plugin/api.md, packages/preset-built-in/src/plugins/generateFiles/core/plugin.ts
=> fix: onRouteChange runtime key

packages/preset-built-in/src/index.ts, packages/preset-built-in/src/plugins/features/publicPath.ts
=> fix: puiblicPath

packages/bundler-webpack/src/webpackHotDevClient/webpackHotDevClient.ts, packages/core/src/Html/Html.ts
=> fix: socket url for back-end server

packages/umi/index.js
=> fix: umi export tmp module in commonjs 

docs/plugin/test.md
=> docs: plugin test

packages/bundler-webpack/src/getConfig/css.ts
=> fix: production build not compress css

packages/core/package.json, packages/core/src/Service/Service.ts, packages/core/src/Service/fixtures/loadDotEnv/.env, packages/core/src/Service/utils/loadDotEnv.test.ts, packages/core/src/Service/utils/loadDotEnv.ts, yarn.lock
=> feat: load dot env

packages/bundler-webpack/src/getConfig/getConfig.ts
=> fix: umi build not add hot client

docs/guide/plugin-api-changes.md, packages/core/src/Service/PluginAPI.ts
=> feat: api.logger.*

docs/plugin/api.md
=> docs: api.logger.*

packages/utils/package.json, packages/utils/src/index.ts, yarn.lock
=> feat: cross-spawn in utils

packages/utils/src/index.ts, packages/utils/src/winEOL/winEOL.test.ts, packages/utils/src/winEOL/winEOL.ts
=> feat: utils add winEOL

packages/preset-built-in/src/plugins/features/globalCSS.ts
=> chore: format require global.css

packages/bundler-webpack/src/fixtures/extraPostCSSPlugins/a.less, packages/bundler-webpack/src/fixtures/extraPostCSSPlugins/config.ts, packages/bundler-webpack/src/fixtures/extraPostCSSPlugins/expect.ts, packages/bundler-webpack/src/fixtures/extraPostCSSPlugins/index.ts, packages/bundler-webpack/src/fixtures/extraPostCSSPlugins/plugin.ts, packages/bundler-webpack/src/getConfig/css.ts, packages/types/index.d.ts
=> feat: extraPostCSSPlugins config

packages/core/src/Route/Route.test.ts, packages/core/src/Route/Route.ts
https://github.com/ant-design/ant-design-pro/pull/5969
=> fix: getRoutes async patch

packages/utils/package.json
=> fix: utils babel deps

packages/create-app/src/index.test.ts
=> chore: add create app jest

packages/test/.fatherrc.ts, packages/test/src/index.ts, packages/test/src/types.ts, packages/test/src/utils/index.ts, packages/test/src/utils/mockConsole.test.ts, packages/test/src/utils/mockConsole.ts
```ts
import { mockConsole } from '@umijs/test';
function sample() {
console.log('a');
console.warn('b');
return 0;
}
test('test sample', () => {
const reset = mockConsole();
expect(sample()).toBe(0);
reset();
expect(reset.messages).toEqual([
['log', 'a'],
['warn', 'b'],
]);
});
test('test sample', () => {
const reset = mockConsole.log();
expect(sample()).toBe(0);
reset();
expect(reset.messages).toEqual([['a']]);
});
```
=> feat(test): new utility 'mockConsole'

.nowignore, .umirc.ts, app.ts, now.json, package.json, packages/umi/tsconfig.json, tsconfig.json
=> feat: now.json

.umirc.ts
=> docs: add custom nav config

packages/preset-built-in/src/plugins/generateFiles/core/history.tpl, packages/preset-built-in/src/plugins/generateFiles/core/history.ts, packages/preset-built-in/src/plugins/generateFiles/umi.tpl
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-next/88)
=> feat: create history while every client rendering

.umirc.ts, package.json
=> docs: use preset-dumi & update config

docs/docs/env-variables.zh-CN.md, packages/bundler-webpack/package.json, packages/bundler-webpack/src/getConfig/getConfig.ts, yarn.lock
通过 `FORK_TS_CHECKER=true` 开启 ts 类型检测：
=> feat: support ts check

docs/plugin/api.md, package.json
=> chore: add repo url into package.json

docs/config/README.zh-CN.md, docs/docs/env-variables.zh-CN.md, modules.d.ts, packages/preset-built-in/package.json, packages/preset-built-in/src/index.ts, packages/preset-built-in/src/plugins/features/analyze.ts, packages/types/index.d.ts, packages/types/package.json, yarn.lock
=> feat: anaylze bundle

docs/config/README.zh-CN.md, packages/bundler-webpack/package.json, packages/bundler-webpack/src/getConfig/getConfig.ts, packages/preset-built-in/package.json, packages/preset-built-in/src/index.ts, packages/preset-built-in/src/plugins/features/forkTSChecker.ts, packages/types/index.d.ts
可通过环境变量 `FORK_TS_CHECKER` 或 `config.forkTSCheker` 配置开启：
=> refactor: fork ts checker in plugin

docs/README.md, docs/README.zh-CN.md, docs/config/README.md, docs/config/README.zh-CN.md, package.json
=> docs: use brand new dumi theme

packages/bundler-webpack/package.json, packages/core/package.json, scripts/bootstrap.ts
修复：首次 bootstrap 时，`description`,`authors`,`files`,`scripts`数据丢失
修改：存在 readme 时，不重写它。这里还是应该写点文档，不然 npm 上全空白很不好
=> fix: bootstrap error

examples/boilerplate/package.json, packages/preset-built-in/src/commands/plugin.ts, packages/preset-built-in/src/index.ts, packages/umi/src/cli/cli.ts, pnpm-lock.yaml
=> feat: umi plugin list

packages/bundler-vite/src/build.ts, packages/bundler-vite/src/config/config.ts, packages/bundler-vite/src/dev.ts, packages/preset-built-in/src/commands/plugin.ts
=> feat:supplement-plugin-list and format

scripts/bundleDeps.ts
=> fix: compiledConfig externals undefined

examples/boilerplate/.umirc.ts, examples/bundler-webpack-esm-demo/config.ts, examples/bundler-webpack-esm-demo/index.html, examples/bundler-webpack-esm-demo/index.tsx, examples/bundler-webpack-esm-demo/package.json, packages/bundler-webpack/src/config/config.ts, packages/bundler-webpack/src/schema.ts, packages/bundler-webpack/src/types.ts, packages/preset-umi/src/commands/build.ts, pnpm-lock.yaml
=> feat: bundler-webpack output support esm

packages/bundler-vite/src/schema.ts, packages/bundler-webpack/src/schema.ts
fix: invalid config keys theme
=> fix: schema add config key theme

packages/core/src/service/generatePlugin.ts
=> fix: generate async error

packages/bundler-webpack/src/swcPlugins/lockCoreJS.test.ts, packages/bundler-webpack/src/swcPlugins/lockCoreJS.ts, pnpm-lock.yaml
=> feat(swc):swc-plugin-lockCoreJS

packages/renderer-react/package.json, packages/renderer-react/src/app.tsx
用 loadable-components 代替 React.lazy + Suspense
=> feat(renderer-react): replace with loadable-components when we support ssr

packages/renderer-react/package.json, packages/renderer-react/src/app.tsx, pnpm-lock.yaml
fix(renderer-react): solve the problem of redrawing caused by suspense
=> fix(renderer-react): solve the problem of redrawing caused by suspense

packages/bundler-esbuild/package.json, packages/bundler-esbuild/src/build.test.ts, packages/bundler-esbuild/src/fixtures/less/path/antd.less, packages/bundler-esbuild/src/fixtures/less/path/antd2.less, packages/bundler-esbuild/src/plugins/less.ts, packages/mfsu/src/dep/dep.ts, pnpm-lock.yaml
修复 less.render 中的 import 路径问题，
存在嵌套 import 的时候，需要它。
增加了一个测试用例。
完善这个[PR](https://github.com/umijs/umi-next/pull/214) 的功能。
=> fix: less render alias

packages/plugins/src/layout.ts
=> fix: icon no found

examples/tmp-swcTranspiler-swc/.umirc.ts, packages/mfsu/src/mfsu.ts
swc 处理不了 mfsu 的顶层异步，两者一起用会报错，这里好习惯包了一下。
另一个 top await 的位置在 `packages/plugins/src/qiankun/master.ts` ，这里面也包了 async ，没问题。
=> fix(mfsu): swc not support top await when use mfsu

examples/ant-design-pro/config/config.ts, examples/ant-design-pro/package.json, examples/ant-design-pro/src/app.tsx, examples/ant-design-pro/src/pages/dashboard/analysis/_mock.ts, examples/ant-design-pro/src/pages/dashboard/analysis/components/IntroduceRow.tsx, examples/ant-design-pro/src/pages/dashboard/analysis/components/OfflineData.tsx, examples/ant-design-pro/src/pages/dashboard/analysis/components/ProportionSales.tsx, examples/ant-design-pro/src/pages/dashboard/analysis/components/SalesCard.tsx, examples/ant-design-pro/src/pages/dashboard/analysis/components/TopSearch.tsx, examples/ant-design-pro/src/pages/dashboard/analysis/data.d.ts, examples/ant-design-pro/src/pages/dashboard/workplace/_mock.ts, examples/ant-design-pro/src/pages/dashboard/workplace/data.d.ts, packages/preset-umi/src/features/mock/getMockData.ts, pnpm-lock.yaml
自定义 mock 配置，并修复 mock 文件中的一些错误的类型定义
=> example(ant-design-pro): chore: types

examples/ant-design-pro/src/pages/list/search/articles/index.tsx, examples/ant-design-pro/src/pages/list/search/index.tsx
修复 react-router@5 升 react-router@6 的一些写法差异
更详细的说明记录在升级备忘中
https://github.com/umijs/umi-next/issues/245#issuecomment-1012694212
=> fix: props match

packages/bundler-esbuild/src/build.ts, packages/bundler-esbuild/src/plugins/style.ts
esbuild 解析字体文件。
Close:  https://github.com/umijs/umi-next/issues/276
=> fix: esbuild support ttf

packages/plugins/src/dva.ts
=> fix: history.listeng of undefined

packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx, packages/plugin-docs/package.json, pnpm-lock.yaml
根据 https://github.com/umijs/umi-next/pull/295#discussion_r789578362 的建议，使用 `classname` 进行代码优化
=> feat(plugin-docs): using classnames package to organize tailwind

packages/plugin-docs/client/theme-doc/Search.tsx, packages/plugin-docs/package.json, pnpm-lock.yaml
1. 实作搜索功能，根据输入的关键字从目录及标题进行查询
2. 支持键盘快捷操作：
- `/` 键即可选中输入框，可直接输入关键字
- `Tab` 和 `Shift + Tab` 上下移动选取结果
- `Enter` 前往该页面
- `Eec` 结束搜索
=> feat(plugin-docs): Added search function

docs/docs/introduce/upgrade-to-umi-4.md
Closes: https://github.com/umijs/umi-next/issues/245
=> docs: upgrade to umi@4

packages/plugin-docs/client/theme-doc/Search.tsx
=> feat(plugin-docs): Search result can select with Up and Down key

packages/bundler-webpack/src/swcPlugins/autoCSSModules.ts, packages/plugins/src/request.ts
修复两个使用 swc 作为 transpiler 时，antd pro 跑不起来的 bug
=> fix(swc): antd pro error with use swc transpiler

packages/bundler-webpack/src/esbuildHandler/autoCssModules.test.ts, packages/mfsu/src/esbuildHandlers/autoExport.test.ts, packages/mfsu/src/esbuildHandlers/autoExport.ts, packages/mfsu/src/esbuildHandlers/awaitImport/awaitImport.test.ts
补齐 esbuild transpiler 链路相关的测试用例。
=> test(esbuild): add esbuild loader handlers test case

packages/bundler-vite/src/config/transformer/alias.test.ts, packages/bundler-vite/src/config/transformer/alias.ts, packages/bundler-vite/src/config/transformer/css.ts
修改了 alias.ts 文件中直接赋值给 alias 导致的数组数据被覆盖的问题。
=> feat(bundler-vite): resolving config overrides

packages/plugin-docs/client/theme-doc/components/Announcement.tsx, packages/plugin-docs/client/theme-doc/firefox-polyfill.css, packages/plugin-docs/client/theme-doc/tailwind.css, packages/plugin-docs/src/compiler.ts
1. 修复了由于 `<Announcement />` 组件导致锚点位置错误的问题（透过 css variable 实现）
2. 将原先带 hash 的 url 也能跳转到锚点的补丁适配到 mdx 2 中
=> feat(plugin-docs): Fixed dynamic anchor bugs

packages/plugin-docs/client/theme-doc/components/FeatureItem.tsx, packages/plugin-docs/client/theme-doc/components/Features.tsx
更改了 `<Features />` 组件的设计，让用户不需要操作也能直接看到全部的 `<FeatureItem />`
=> Feature/plugin: Adjusted <Featurs /> component layout

packages/bundler-webpack/src/config/config.ts, packages/bundler-webpack/src/constants.ts, packages/preset-umi/src/commands/config/list.ts, packages/preset-umi/src/commands/dev/createRouteMiddleware.ts, packages/preset-umi/src/features/configPlugins/configPlugins.ts
=> chore(preset): extract browser targets var

docs/docs/guides/prepare.md
完成了「开发环境」 (`docs/guide/prepare.md`) 文档的编写。
=> docs: Updated docs/guide/prepare.md

docs/docs/guides/directory-structure.md
=> docs: directory-structure

packages/utils/src/npmClient.ts
windows和mac行为不一致，原有方案在windows下会报错。
close https://github.com/umijs/umi-next/issues/391
=> fix(@umi/utils): add the windows support

packages/preset-umi/src/features/configPlugins/configPlugins.ts
修复 vite 模式下配置文件 schema 校验不生效的问题
Close #401
=> fix(preset-umi): enable vite schema for vite mode

docs/docs/guides/mock.md
完成了 Mock 的文档
https://umi-next-git-docs-mock-umijs.vercel.app/zh-CN/docs/guides/mock
=> docs: mock

packages/create-umi/src/index.ts
=> fix(create-umi-app): Fix typo "Bpm" to "Npm"

docs/docs/guides/boilerplate.md
=> docs:boilerplate

packages/preset-umi/src/features/lowImport/babelPlugin.test.ts, packages/preset-umi/src/features/lowImport/babelPlugin.ts
=> feat: multiple same identifier only  import one

scripts/turbo.ts
=> build: force build ignore cache option

packages/bundler-vite/src/dev.ts, packages/bundler-vite/src/server/server.ts
=> fix(bundler-vite): port-in-use

packages/bundler-vite/src/config/transformer/index.ts, packages/bundler-vite/src/config/transformer/merge.ts
=> feat(bundler-vite): add merge viteConfig from userConfig

packages/preset-umi/src/features/apiRoute/apiRoute.ts
让 `umi dev` 开发模式下支持动态增删 API 路由，当用户在 `api` 目录下加入新文件或删除原有文件时，将会调用 `api.restartServer()` 重启服务。
有一个更有效率的做法是：不重启服务，当监听到文件变更时，先更新 `api.appData.apiRoutes` 内的数据，再重新生成 `.umi/api` 目录下的临时文件，当 esbuild 发现 `.umi/api` 目录下有变化，就会直接重新打包。
但不确定要不要这样做，这个方案感觉把 API 路由功能的生命周期和 Umi 插件系统脱钩了
=> feat(api-routes): watch api route created or deleted in `umi dev`

docs/docs/api/config.md, packages/bundler-vite/src/config/transformer/index.ts, packages/bundler-vite/src/config/transformer/merge.ts
=> docs: add vite config

packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
修复 exports types 在 win 系统上的 winPath 问题
=> fix: export types winpath

packages/core/src/service/pluginAPI.ts
=> feat(core): pluginAPI registerPresets plugin type correction

packages/preset-umi/src/commands/config/config.ts
修复 umi config set 在无配置文件时报错的问题，执行 config set 时如果没有找到配置文件，默认生成一个
=> feat: fix config set

scripts/turbo.ts
=> fix(turbo): extra options position

packages/plugins/src/tailwindcss.ts, packages/plugins/src/unocss.ts
for https://github.com/umijs/umi-next/issues/482#issue-1169076105  
Close #482
=> refactor(plugins): 🎨 css related plugin only run in dev or build

examples/with-sass/.umirc.ts, examples/with-sass/package.json, examples/with-sass/pages/index.scss, examples/with-sass/pages/index.tsx, examples/with-sass/readme.md, examples/with-sass/tsconfig.json, examples/with-sass/typings.d.ts, pnpm-lock.yaml
for issue https://github.com/umijs/umi-next/issues/487
=> feat: ✨ add with-sass example

packages/server/package.json, pnpm-lock.yaml
修复 server 中的 bundler-utils 没走 monorepo 版本的 bug
=> fix(server): correct bundler-utils version

examples/with-sass/package.json, scripts/checkPackageFiles.ts, scripts/release.ts
1. 把 check `package.json` 信息的脚本加上
2. 提升 `version` 的重复代码抽出函数
=> chore: improve release check method

packages/preset-umi/src/commands/generators/dva.ts, packages/preset-umi/src/commands/generators/jest.ts, packages/preset-umi/src/commands/generators/prettier.ts, packages/preset-umi/src/commands/generators/tailwindcss.ts, packages/preset-umi/src/commands/generators/tsconfig.ts, packages/preset-umi/src/commands/generators/utils.ts
提取 GeneratorHelper 避免过多的重复
简化具体的 generator 中的实现
=> 优化 generators

docs/docs/tutorials/blog.md
增加了文档：开发一个 Blog
https://umi-next-git-docs-blog-umijs.vercel.app/zh-CN/docs/tutorials/blog
=> docs: Add tutorials/blog.md

packages/core/src/service/service.ts, packages/umi/package.json, packages/umi/src/client/plugin.test.ts, packages/umi/src/client/plugin.ts
=> 移除 isPromise 判断  代码更加直接

packages/bundler-webpack/package.json, packages/bundler-webpack/src/swcPlugins/autoCSSModules.ts, packages/bundler-webpack/src/swcPlugins/changeImportFromString.ts, packages/bundler-webpack/src/swcPlugins/lockCoreJS.ts, pnpm-lock.yaml
swc Breaking change
See https://github.com/swc-project/swc/issues/4128
=> fix(swc): sync change to `raw` for string literal type

packages/bundler-webpack/src/server/server.ts
替换 sync 的 io 使用 stream 不阻断 node 主线程（一个几乎感受不到的性能优化
=> 读代码中一些零碎的小修改

package.json, packages/bundler-webpack/client/client/client.js, packages/bundler-webpack/client/constants.js, packages/umi/client/client/plugin.js, scripts/release.ts, turbo.json
1. 在 release 脚本中构建 client 代码，如果变动终止发布
2. 更新 umi/client 代码
3. 更新 bundler-webpack/client 代码，async 函数被 transpile 了 （@sorrycc  看看这个有没有必要更新
3 如果 bundler-webpack 暂不更新的话，我就限制下 scope 只搞 umi client
=> client 端代码更新机制

examples/bigfish/.umirc.ts, examples/bigfish/app.ts, examples/bigfish/components/Loading/index.less, examples/bigfish/components/Loading/index.tsx, packages/plugins/src/initial-state.ts
plugin-initial-state 设置自定义loading 报错处理
=> fix(plugin-intial-state): custom loading error

examples/remix/config/config.ts, packages/bundler-vite/src/config/transformer/target.ts, packages/bundler-vite/src/fixtures/alias/config.ts
vite 模式 esbuild target 不支持ios 设置
=> fix(bundler-vite): esbuild target does not support ios

packages/preset-umi/src/commands/dev/getBabelOpts.ts
修复 React 17 以下的项目 babel 编译出错的问题
=> fix(preset-umi): babel build faild if react<17

packages/create-umi/templates/app/pages/index.tsx, packages/create-umi/templates/app/typings.d.ts
vite 模式不支持require 改成import 的方式
=> feat(create-umi): template support vite

packages/preset-umi/src/commands/generators/api.test.ts, packages/preset-umi/src/commands/generators/api.ts, packages/preset-umi/src/commands/generators/component.test.ts, packages/preset-umi/src/commands/generators/component.ts, packages/preset-umi/src/commands/generators/mock.ts, packages/preset-umi/src/commands/generators/page.ts, packages/preset-umi/src/commands/generators/utils.ts, packages/preset-umi/src/index.ts, packages/preset-umi/templates/generate/api.ts.tpl, packages/preset-umi/templates/generate/component/component.tsx.tpl, packages/preset-umi/templates/generate/component/index.ts.tpl, packages/preset-umi/templates/generate/mock.ts.tpl
```
umi g component  table tab title
info  - @local
Write: components/Table/index.ts
Write: components/Table/Table.tsx
Write: components/Tab/index.ts
Write: components/Tab/Tab.tsx
Write: components/Title/index.ts
Write: components/Title/Title.tsx
```
```
umi  g component  member/{avatar,level}
info  - @local
Write: components/member/Avatar/index.ts
Write: components/member/Avatar/Avatar.tsx
Write: components/member/Level/index.ts
Write: components/member/Level/Level.tsx
```
```
g mock auth
info  - @local
Write: mock/auth.ts
```
`mock/auth.ts` content 
```ts
export default {
// you can mock api simply return a json
'GET /api/auth-json': {
success: true,
data: {
users: [{ name: 'admin' }, { name: 'test' }],
},
},
// you can also use a express  middleware to mock the api
'GET …
```
=> Feat: api  mock  component generator

packages/plugin-docs/src/index.ts
=> fix(plugin-docs): winPath

docs/docs/max/data-flow.md, docs/docs/max/i18n.md
- 添加了 `@umi/max` 的数据流使用文档。
- 更新了国际化章节的部分内容。
=> docs(data-flow): add user guide for data-flow (@umijs/plugins-model)

docs/blog/mfsu-independent-usage.md, docs/docs/api/config.md, docs/docs/max/data-flow.md
1. resolve #598
2. fix https://github.com/umijs/umi-next/commit/0db6d8470a6dc152b48052aca79f3fc120a70f28 commit syntax error
3. update mfsu options table
=> docs: fix typo and others (resolve #598)

docs/docs/api/config.md
=> fix: 文档中配置API存在错别字

packages/max/package.json, pnpm-lock.yaml
`@umijs/max` 内置 eslint 和 stylelint 的依赖
=> refactor(max): built-in stylelint & eslint in max

packages/umi/client/client/plugin.js, packages/umi/client/client/utils.js, packages/umi/tsconfig.client.json
// CONCATENATED MODULE: ./node_modules/.pnpm/umi@4.0.0-canary.20220412.3_d46e6c1ddbc73ec4a2cf77e9e3d6bb18/node_modules/umi/client/client/utils.js
SCRIPT1010: 缺少标识符
1、修改 packages/umi/tsconfig.client.json "target": "ES5",
2、执行 `build:client`
=> feat: umi/client browser compatible

packages/preset-umi/src/features/devTool/devTool.ts
修复 vite 模式 dev loading 无法结束
> 原因是 mfsu 默认是开启(或者当用户配置指定mfsu 模式开启的情况) 开启vite 模式 mfsuBundleStatus 状态永远无法done
=> fix(preset-umi): dev loading

docs/docs/guides/styling.md
增加了在 Umi 4 使用样式的教学文档。
https://umi-next-git-docs-style-umijs.vercel.app/zh-CN/docs/guides/styling
=> 📝 Docs/styling

docs/docs/guides/typescript.md
增加了 Umi 4 的 Typescript 文档。
https://umi-next-git-docs-typescript-umijs.vercel.app/zh-CN/docs/guides/typescript
=> 📝 Docs/typescript

docs/docs/guides/lint.md
=> docs: add lint guide

docs/docs/max/layout-menu.md
=> docs: 📝 layout-memu 文档 

docs/docs/max/antd.md
=> docs: 📝 antd 文档

packages/bundler-webpack/src/schema.ts
=> refactor: 🎨 add msfu#runtimePublicpath boolean config

packages/mfsu/src/mfsu.ts
修复 mfsu `publicPath` 问题
resolve #637
=> fix(mfsu): remote entry `publicPath` prefix (resolve #637)

docs/docs/api/plugin-api.md, packages/preset-umi/src/features/transform/babelPlugin.test.ts, packages/preset-umi/src/features/transform/babelPlugin.ts, packages/preset-umi/src/types.ts
接 #646 ，增加 `import` / `import type` 的区分支持
=> feat(preset-umi): add importKind for onCheckCode import

scripts/release.ts
=> chore: release script support npm otp

packages/plugin-docs/client/theme-doc/tailwind.css
- 修复了在包含代码块的页面拖动滚动条时，滚动条抖动的问题。
- 修复了代码块语言固定的问题。
=> fix(plugin-docs): fix scrollbar jitter & fix code block language position

packages/plugin-docs/client/theme-doc/Sidebar.tsx
=> fix: 🐛 add missing key prop

packages/preset-umi/assets/bundle-status.html, packages/preset-umi/src/features/devTool/devTool.ts
添加 dev 启动 loading 界面的动画，且支持通过 Plugin API 修改 HTML 内容，效果如下：
=> feat(preset-umi): add dev loading animation

docs/docs/max/request.md
=> fix(plugin-docs): request typo

docs/docs/api/api.md
谢谢 各位老哥老妹 鼎力相助 
@hanzebang  @ken20001207  @stormslowly  @YdreamW  @devilmancbc
=> docs: 📝  Umi api 文档更新

docs/docs/api/config.md, packages/bundler-vite/src/config/transformer/react.ts, packages/bundler-vite/src/schema.ts, packages/bundler-webpack/src/build.test.ts, packages/bundler-webpack/src/build.ts, packages/bundler-webpack/src/config/config.ts, packages/bundler-webpack/src/config/javaScriptRules.ts, packages/bundler-webpack/src/dev.ts, packages/bundler-webpack/src/fixtures/extra-babel-includes/config.ts, packages/bundler-webpack/src/fixtures/extra-babel-includes/index.ts, packages/bundler-webpack/src/fixtures/extra-babel-includes/node_modules/@group/decorator/index.js, packages/bundler-webpack/src/fixtures/extra-babel-includes/node_modules/@group/decorator/package.json, packages/bundler-webpack/src/fixtures/extra-babel-includes/node_modules/jsx/index.js, packages/bundler-webpack/src/fixtures/extra-babel-includes/node_modules/jsx/package.json, packages/bundler-webpack/src/fixtures/extra-babel-includes/node_modules/unicode-reg/index.js, packages/bundler-webpack/src/fixtures/extra-babel-includes/node_modules/unicode-reg/package.json, packages/bundler-webpack/src/schema.ts, packages/bundler-webpack/src/types.ts
支持 `extraBabelIncludes` 配置项，与 Umi 3 功能一致
=> feat: support extraBabelIncludes config

packages/plugin-docs/client/theme-doc/Sidebar.tsx, packages/plugin-docs/src/compiler.ts
优化 `plugin-docs` 的用户体验，左侧导航栏会自动滚动到选中的位置
=> feat(plugin-docs): scroll side nav to selected position

packages/create-umi/templates/app/tsconfig.json
fix  https://github.com/umijs/umi-next/pull/583#issuecomment-1111680308
=> fix: 🚑 默认带 src 目录，tsconfig alias 保持一致

packages/renderer-react/src/index.ts
导出 `Navigate` 组件，以便在 `patchClientRoutes` 里设置 redirect
=> feat: export Navigate for redirect

packages/plugins/libs/qiankun/master/common.ts, packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl, packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
修复 qiankun 插件在 runtime patchRoutes 失败导致主应用无法激活的问题
=> fix(plugins): patch runtime routes bug in qiankun

packages/plugins/libs/qiankun/master/common.ts, packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl
1. 修复 qiankun 子应用挂载路由无法匹配子路径的问题
2. 修复 qiankun 子应用子路径挂载时 router base 错误的问题
=> fix(plugins): qiankun slave router base & path match

packages/plugins/libs/qiankun/master/common.ts, packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
=> fix(plugins): typo bug in qiankun

docs/docs/guides/routes.md, docs/docs/max/data-flow.md, docs/docs/max/layout-menu.md, docs/docs/max/micro-frontend.md
*  loading.tsx 按需加载 loading 自建 convention 介绍
*  重命名 @umijs/plugin-xxxx 为 插件 ，带上对应链接
=> docs: 📖  日常文档更新

packages/plugin-docs/src/markdown.ts
=> fix(plugin-docs): Fix #751 commented title still appears in TOC

examples/lint/package.json, pnpm-lock.yaml, scripts/release.ts
修复 release 同步版本号的时候没刷到 dev deps
=> fix(release): dev deps version sync

packages/plugins/src/request.ts
修复 request 插件，`errorConfig.errorThrower` 在请求成功时也会调用的问题
=> fix(plugins): correct error handler called logic

docs/locales/zh-CN.json, packages/plugin-docs/client/theme-doc/Search.tsx
=> fix(plugin-docs): Show "No result" in search input

packages/mfsu/src/dep/dep.ts
=> refactor: 🎨 in case some npm published ts/tsx

packages/preset-umi/src/features/favicons/favicons.ts, packages/preset-umi/src/index.ts
修正 favicons 的 schema，目前配置 `favicons` 会报错
=> fix(preset-umi): favicon schema

examples/boilerplate/.umirc.ts, examples/boilerplate/pages/users/foo.tsx, examples/boilerplate/pages/users/login/index.tsx, packages/core/src/route/routesConfig.ts
子路由忘记处理 `onResolveComponent`  会导致routes 下路由配置未处理
=> fix(core): routesConfig children route add onResolveComponent

docs/docs/max/charts.md, examples/ant-design-pro/mock/user.ts, examples/ant-design-pro/src/pages/account/center/_mock.ts, examples/ant-design-pro/src/pages/account/center/components/Articles/index.tsx, examples/ant-design-pro/src/pages/account/settings/_mock.ts, examples/ant-design-pro/src/pages/dashboard/workplace/index.tsx, examples/ant-design-pro/src/pages/list/basic-list/_mock.ts, examples/ant-design-pro/src/pages/list/card-list/_mock.ts, examples/ant-design-pro/src/pages/list/card-list/index.tsx, examples/ant-design-pro/src/pages/list/search/applications/_mock.ts, examples/ant-design-pro/src/pages/list/search/articles/_mock.ts, examples/ant-design-pro/src/pages/list/search/articles/index.tsx, examples/ant-design-pro/src/pages/list/search/projects/_mock.ts
=> chore: 🎨 蚂蚁金服 -> 蚂蚁集团

packages/utils/src/register.ts
解使用高阶语法（如 for await）现转换目标不支持的问题
=> chore(utils): up esbuild transform target

docs/docs/api/api.md, docs/docs/introduce/upgrade-to-umi-4.md, packages/renderer-react/src/index.ts
=> feat: export useOutletContext

packages/lint/src/linter/base.ts
=> fix(lint): exit code when lint error

packages/bundler-webpack/src/server/server.ts
=> feat(bundler-webpack): ✨ make all .js file can be replaced and debug in dev mode

packages/preset-umi/src/commands/dev/dev.ts
=> feat: ✨ dev 启动不移除临时文件 只覆盖原来的文件

packages/plugins/src/request.ts
=> fix: plugin-request

examples/max/pages/use-model.tsx, packages/plugins/libs/model.tsx, packages/plugins/src/utils/modelUtils.ts
=> feat(plugin-model): improve useModel types definition

docs/docs/api/api.md, packages/renderer-react/src/appContext.ts, packages/renderer-react/src/link.tsx, packages/renderer-react/src/routeContext.ts, packages/renderer-react/src/routes.tsx, packages/renderer-react/src/types.ts
完善 useAppData 和 useRouteData 的类型，现在是 any
=> Fix(render react)完善use app data和use route data类型

packages/preset-umi/src/features/vite/vite.ts, packages/preset-umi/src/utils/transformIEAR.test.ts, packages/preset-umi/src/utils/transformIEAR.ts
=> fix(preset-umi): fix bugs caused by vite @fs

examples/vue-demo/pages/index.vue, packages/preset-umi/src/commands/dev/createRouteMiddleware.ts, packages/preset-umi/src/commands/dev/dev.ts, packages/preset-umi/src/commands/dev/plugins/ViteHtmlPlugin.ts
- 修复从webpack 切换到vite 模式自动重启进程卡死
- 修复vite 模式 加载错误资源(如图片) 导致的进程卡死
=> feat(preset-umi): optimize createRouteMiddleware fix vite load error image process stuck

packages/preset-umi/src/commands/dev/dev.ts
修复 无法通过 api.addMiddlewares 对页面请求做前置处理
=> fix(preset-umi): dev createRouteMiddleware

package.json, packages/father/examples/normal/.fatherrc.ts, packages/father/examples/normal/src/content.tsx, packages/father/examples/normal/src/index.tsx, packages/father/examples/normal/tsconfig.json, packages/father/package.json, packages/father/src/builder/bundless/index.ts, packages/father/src/builder/bundless/loaders/index.ts, packages/father/src/builder/bundless/loaders/javascript/babel.ts, packages/father/src/builder/bundless/loaders/javascript/index.ts, packages/father/src/builder/bundless/loaders/javascript/resolvePath.ts, packages/father/src/builder/protocol.ts, packages/father/src/features/configBuilder/configBuilder.ts, pnpm-lock.yaml
1. Improve babel transformer including presets and plugin;
2. Add test for babel transformer with examples/normal.
=> add babel transformer

docs/docs/api/config.md
一些场景需要使用到 less@3 编辑，默认的配置不兼容，文档里面增加提示
https://github.com/ant-design/ant-design/issues/23125#issuecomment-757678485
=> docs: less@3 support

packages/preset-umi/src/commands/dev/dev.ts
=> Revert "feat: ✨ dev 启动不移除临时文件 只覆盖原来的文件"

packages/plugins/libs/qiankun/master/MicroApp.tsx, packages/plugins/libs/qiankun/master/types.ts
sync from https://github.com/umijs/plugins/pull/863
=> feat(qiankun): 新增 appNameKeyAlias 支持为微应用取 name 之外的别名主键

packages/plugins/src/access.ts
现状：父路由组件设置权限，子组件未设置权限，子组件不渲染。
期望： 子组件未设置权限，沿用父组件的权限设置。
=> fix(plugin-access): check children access

docs/docs/api/runtime-config.md
=> docs: 📝 runtime api 订正

packages/plugins/src/initial-state.ts, packages/plugins/src/layout.ts
* 增加 initialValues 的类型
* 增加 RunTimeLayoutConfig 类型
=> fix(layout): add initialValues and layout types

docs/docs/max/data-flow.md, packages/plugins/src/utils/modelUtils.test.ts
* 增加 namesapce 的生成的表格说明
* 移除已经失效的 singular 配置说明
* model 命名 不提倡 useXXXX.ts 的形式
=> docs: 📝  data-flow 文档更新

docs/docs/api/config.md
=> docs: fix typo

packages/preset-umi/src/commands/generators/cypress.ts, packages/preset-umi/src/commands/generators/utils.ts, packages/preset-umi/src/index.ts, packages/preset-umi/templates/generate/cypress/e2e/example.cy.ts.tpl, packages/preset-umi/templates/generate/cypress/fixtures/example.json, packages/preset-umi/templates/generate/cypress/support/commands.ts.tpl, packages/preset-umi/templates/generate/cypress/support/e2e.ts.tpl
generate cypress config for umi  project
```
? Pick generator type › - Use arrow-keys. Return to submit.
Create Pages -- Create a umi page by page name
Enable Dva -- Configuration, Dependencies, and Model Files for Dva
Generate Component -- Generate component boilerplate code
Generate mock -- Generate mock boilerplate code
❯   Enable E2E Testing with Cypress -- Setup Cypress Configuration
Generator api -- Generate api route boilerplate code
info  - Update package.json for devDependencies
info  - Update package.json for scripts
info  - Update .gitignore
info  - Write cypress.config.ts
Write: cypress/e2e/example.cy.ts
Copy:  fixtures/example.json
Write: cypress/support/commands.ts
Write: cypress/support/e2e.ts
```
=> feat(generator): cypress

docs/docs/guides/use-vue.md, theme.config.ts
=> docs(guides): add use vue

docs/docs/guides/boilerplate.md, docs/docs/guides/prepare.md, docs/docs/tutorials/getting-started.md
Since the usage in pnpm 6 has been changed
=> chore: use latest pnpm 7

docs/docs/api/api.md
https://github.com/umijs/umi/issues/8168
=> docs(docs/api/api): 错别字

packages/create-umi/templates/app/src/layouts/index.tsx.tpl, packages/create-umi/templates/app/src/pages/docs.tsx, packages/create-umi/templates/app/src/pages/index.tsx, packages/create-umi/templates/max/src/pages/Access/index.tsx, packages/create-umi/templates/max/src/pages/Home/index.tsx
=>   这些初始化页里没有用到React，不需要引入。

packages/core/src/route/routesConvention.test.ts, packages/core/src/route/routesConvention.ts
保持 Umi@3 中的约定，index/index 会被识别成首页。
=> feat: replace index

docs/docs/guides/boilerplate.md, docs/docs/tutorials/getting-started.md
=> docs: update

docs/docs/api/config.md
=> docs: completing preprocess style loader config
