- package.json
- scripts/release.js
- scripts/syncTNPM.js
1. 发布时同步发布的模块
2. 执行 `npm run sync:tnpm` 同步所有的 umi 模块
3. 也可以执行 `node -e 'require("./scripts/syncTNPM")(["core"])'` 来同步某个模块
> chore: sync tnpm packages when published

- packages/preset-built-in/src/plugins/commands/dev/mock/mock.ts
- packages/server/src/Server/Server.ts
1. proxy 修复，需要在 mock 后执行
2. proxy 增加了 res header `x-real-url` ，方便排查问题
3. 补充 `MOCK` 和 `HTTP_MOCK` 环境变量
> fix: proxy should run behind mock

- docs/plugin/api.md
- packages/core/src/Html/types.d.ts
- packages/preset-built-in/src/fixtures/html/.umirc.ts
- packages/preset-built-in/src/fixtures/html/mode.ts
- packages/preset-built-in/src/fixtures/html/plugin.ts
- packages/preset-built-in/src/index.test.ts
- packages/preset-built-in/src/plugins/commands/dev/createRouteMiddleware.ts
- packages/preset-built-in/src/plugins/commands/dev/dev.ts
- packages/preset-built-in/src/plugins/commands/htmlUtils.ts
- packages/preset-built-in/src/plugins/registerMethods.ts
1. 优化 dev 使用 chunks
1. 增加 `modifyHTMLJSFiles` 和 `modifyHTMLHeadJSFiles` API，用于添加 entry chunk js 文件到 html
> fix: dev chunks using compiler

- examples/boilerplate/.umirc.ts
- packages/create-umi/bin/create-umi.js
- packages/create-umi/src/index.ts
- packages/create-umi/templates/app/.npmrc.tpl
- packages/create-umi/templates/app/.umirc.ts
- packages/create-umi/templates/app/.umirc.ts.tpl
- packages/create-umi/templates/plugin/.npmrc.tpl
- packages/preset-built-in/src/features/appData/appData.ts
- packages/preset-built-in/src/features/configPlugins/schema.ts
- packages/utils/src/index.ts
- packages/utils/src/npmClient.ts
1. type NpmClient = 'npm'l'cnpm' l'tnpm'l'yarn'l'pnpm'
2. utils 里提供 npmClient.ts，提供如下方法
3. checkNpmClient: NpmClient 检测指定的 npm client 是否可用
4. installWithNpmClient(opts: { npmClient: NpmClient}) 使用指定的 npm client 进行安装，建议调用前先调用checkNpmClient
5.getNpmClient 获取当前可用的 npm client (pnpm-tnpm-yarn-cnpm-npm)
1. 新增配置 npmClient，创建脚手架时让选择，首选 pnpm，-npmrc 里的registry 也可以让选择
2. builtin 的appData.ts 里加上 memo.npmClient，优先用配置里的，没有走 utils. getNpmClient 检测获取
> 3. generator 里安装依赖时直接用 api.appData.npmClient + installWithNpimClient 的组合
>（本次 PR，没有第3点的任何代码）
> feat: add npmClient

- packages/bundler-esbuild/src/build.test.ts
- packages/bundler-esbuild/src/build.ts
- packages/bundler-esbuild/src/fixtures/externals/config.ts
- packages/bundler-esbuild/src/fixtures/externals/index.ts
- packages/bundler-esbuild/src/plugins/externals.ts
增加 esbuild externals 配置
@linbudu599 思路：将配置中的包名，通过 `module.export=` 关联到 window 对象上。
> feat: esbuild externals

- packages/preset-umi/src/features/tmpFiles/routes.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
windows 上 .umi 内生成的文件如下
将引发以下报错
生成 `template` 文件部分使用 `winPath` 函数对路径类参数做处理
> fix: path error of template files on windows

- packages/bundler-vite/package.json
bundler-vite 包发布时未携带 compiled 导致的报错
bundler-vite 包中 package.json/files 字段上补充 compiled 文件夹
> fix: files lost in npm dist

- packages/bundler-webpack/src/server/ws.ts
`bundler-webpack` 包中 `src/server/ws.ts` 内所使用的 `ws` 为 `node_modules` 导入，且将在 `umi dev` 运行命令中被使用
但 `package.json` 中 `ws` 为 `devDependencies` 开发时依赖，造成使用时出现以下错误
1. 将 `ws` 声明为 `dependencies` 运行依赖，有额外下载成本
2. `ws` 改为从 `bundler-webpack/compiled` 中导入
依赖声明中 ws 为 8.2.3 版本，看到 compiled 包内版本为 8.2.x，猜测建议方案为方案 2
> fix: import ws from compiled dir

- packages/core/src/service/service.ts
- packages/preset-umi/package.json
- packages/preset-umi/src/features/esmi/Service.ts
- packages/preset-umi/src/features/esmi/esmi.ts
- packages/preset-umi/src/types.ts
- pnpm-lock.yaml
包含 esmi bundless CDN 接入的基础能力：
1. esmi service 请求模块
2. esmi feature 插件部分
1. 获取、更新、插入 importmap
2. 通过内置 vite plugin 控制 vite 的预编译行为 + 替换依赖引入为 importmap 的 CDN 地址（后续看下这步能不能拿掉）
**使用方式：**
在 `.umirc.ts` 里配置 `esmi: { cdnOrigin: '内部服务的地址' }` 即可
留下的 TODO，已在源码里标记：
> feat: basic esmi feature

- packages/preset-umi/src/features/esmi/Service.ts
- packages/preset-umi/src/features/esmi/esmi.ts
优化 esmi（bundless CDN）接入的能力，包含上一个 PR #204 中的部分 TODO：
1. importmap 支持本地缓存，根据 `pkgInfo` 做识别，只要依赖没有变化就优先使用缓存
2. 添加 esmi 依赖预编译的输出信息，包括预编译依赖列表以及耗时
3. 预编译强制包含 `react` 和 `react-dom`，避免出现这两个依赖版本不一致或缺失的情况
4. importmap 的 url 都预先添加 `modulepreload`
5. 支持定制 shim 脚本兼容低版本浏览器
> feat: local cache & improvements for esmi

- packages/preset-umi/src/commands/dev/createRouteMiddleware.ts
- packages/server/src/server.ts
Vite 模式的 dev 脚本（@vite/client 等）添加 `noshim` 标记，防止被 ESMi 的 importmap shim 处理导致浏览器卡死
> feat(preset-umi): noshim for dev scripts in vite mode

- packages/bundler-esbuild/src/build.test.ts
- packages/bundler-esbuild/src/build.ts
- packages/bundler-esbuild/src/fixtures/less/config.ts
- packages/bundler-esbuild/src/fixtures/less/index.less
- packages/bundler-esbuild/src/fixtures/less/index.ts
- packages/bundler-esbuild/src/fixtures/less/path/antd.less
- packages/bundler-esbuild/src/plugins/less.ts
- packages/preset-umi/src/types.ts
修复 bundler-esbuild 处理 less 时，如果是 alias 的，会找不到。
比如 @import '~antd/es/style/themes/index.less'， antd 是 alias 的。
> fix: less import alias error

- examples/bigfish/.umirc.ts
- packages/bundler-esbuild/src/build.ts
- packages/bundler-esbuild/src/plugins/less.ts
- pnpm-lock.yaml
1、修复 less 文件的 import 路径问题（包含别名和相对路径）
2、修复 esbuild less style lost 问题
```
1. examples/bigfish 下开启配置 mfsu: { esbuild: true }
2. rm -rf .mfsu && npm run dev
```
1、esbuild 不解析 less 文件
2、less 文件的引用别名问题
3、esbuild 不加载 css 样式问题
1、使用 less.render 编译 less 文件，通过自定义插件中使用的 `less.render` 就可以将 less 文件转化为 css 文件。这部分思路参考了 https://github.com/iam-medvedev/esbuild-plugin-less/blob/528414ac5d0eb6280713adc8ca33e38184628f4c/src/index.ts#L29
```ts
onLoad({ filter: /\.less$/, namespace: 'file' }, (args) => {
let content = await fs.readFile(args.path, 'utf-8');
return {
contents: less.render().css,
loader: 'css',
resolveDir: dir,
};
}
```
2、在上面的解析 less 的过程中，我们使用 `readFile` 直接读取了文件中的内容，然后通过 `less`解析，通过 `@import` 和 `less rootpath` 的规则，没有办法找到我们定义的别名（alias），所以我们需要先处理一下读取出来的字符串，将 `import` 的正确路径匹配。
```
if (!!alias) { …
```
> fix: less import and style lost

- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/config/harmonyLinkingErrorPlugin.ts
Related Issue：https://github.com/umijs/umi-next/issues/116
bundler-webpack
```typescript
// test.ts
import { A } from './not-found';
console.log(A);
```
current behavior:
`pass build`
after pr:
throw error like this:
```bash
error - ./index.tsx:13:19-20
export 'A' (imported as 'A') was not found in './not-found' (possible exports: default)
```
> feat: add HarmonyLinkingErrorPlugin

- packages/core/src/service/service.ts
可以通过 `config` 里面的配置来跳过插件，一般是使用 `modifyConfig` 和 `modifyDefaultConfig` 来控制插件的启用情况
> feat: skipPlugin by config

- packages/bundler-vite/src/config/transformer/css.ts
修复无法在 Less 文件中使用 `~` 前缀引入 alias 中的依赖的 bug
> fix(bundler-vite): cannot import alias deps in less

- packages/bundler-vite/src/config/config.ts
- packages/bundler-vite/src/config/transformer/optimizeDeps.ts
设置正确的 `optimizeDeps.entries` 以启用 vite 自带的依赖扫描
> fix(bundler-vite): set optimize entries for pre-bundling deps

- packages/bundler-vite/package.json
- packages/preset-umi/package.json
- packages/preset-umi/src/features/configPlugins/configPlugins.ts
- packages/preset-umi/src/registerMethods.ts
- packages/preset-umi/src/utils/transformIEAR.test.ts
- packages/preset-umi/src/utils/transformIEAR.ts
- pnpm-lock.yaml
优化 `writeTmpFile` api，自动转换 import/export/await-import/require 的绝对路径为相对路径（`.umi` 下的引入）或 `@fs` 前缀（`node_modules` 下的引入），以便支持 vite 扫描正确扫描依赖。
尝试各种方案后，语句识别采用了正则匹配，并通过表达式拆分 + 测试用例尽量保证可维护性，但推测仍有边界 case，未来遇到了再看。
其他方案的问题：
1. `es-module-lexer`，能准确识别 import 语句的位置，但不支持 JSX，识别会报错
2. `esbuild`，支持 JSX，但无法准确识别 import 语句的位置并且做替换，用 replace 很容易误触发
> feat(preset-umi): better write tmp file api for vite mode

- packages/preset-umi/src/utils/transformIEAR.test.ts
- packages/preset-umi/src/utils/transformIEAR.ts
修复 `writeTmpFile` 时 `.umi` 下同级/子级的绝对路径引入缺少头部 `./` 导致 import 失败的 bug
> fix(preset-umi): head dot lost for relative path in writeTmpFile

- packages/bundler-vite/src/config/transformer/alias.ts
- packages/bundler-vite/src/config/transformer/css.ts
- packages/bundler-vite/src/config/transformer/index.ts
- packages/bundler-vite/src/config/transformer/rename.ts
- packages/core/src/service/service.ts
- packages/plugins/src/request.ts
- packages/preset-umi/src/features/esmi/esbuildPlugins/requireToImport.ts
- packages/preset-umi/src/features/esmi/esbuildPlugins/topLevelExternal.ts
- packages/preset-umi/src/features/esmi/esmi.ts
- packages/preset-umi/src/libs/scan.ts
- packages/preset-umi/src/registerMethods.ts
完善 esmi 及相关功能以支持 Bigfish 示例项目，主要改动点如下：
1. scan 阶段采集 import paths，并且区分 entry match 和 sub-path match
2. 根据 scan 的结果，不对 entry match 做预编译（例如绝对路径引入 entry 和包名引入是等价的）
3. 根据 scan 的结果，额外挂载 esbuild 插件实现不对 sub-path match 做 external，以便走本地编译
3. 额外挂载 esbuild 插件，将已被 external、又被 require 引入的依赖转换为 import 引入，确保可以在浏览器环境和 `importmap` 一起 work
与项目跑通有关的附带改动点：
1. bundler-vite 的 alias 配置转换支持 webpack 的 `$` 修饰符，并且将 less-loader 的 `~` 一并用正则匹配处理了
2. plugin-request 的临时 `request.ts` 中对 axois 类型的引入加上 type 标识符，否则会导致在浏览器环境支持的时候从 CDN 产物中找不到导出
TODO：
1. 临时文件用 `@fs` 访问绝对路径会丢失类型，初步确定 tsconfig.json 里加个 paths
2. antd 的样式目前不走云构建，本地得做白名单引入
> feat: complete esmi for bigfish example

- packages/preset-umi/src/features/mock/fixtures/normal/mock/b.ts
- packages/preset-umi/src/features/mock/getMockData.test.ts
- packages/preset-umi/src/features/mock/getMockData.ts
```
'GET  /api/login/captcha':  (req: Request, res: Response) => {return res.json('captcha-xxx');},
```
中间的有多个空格的时候，被识别成 `[method, path]` ，path 是空的，就会覆盖掉请求。
`http://localhost:8000/ ===>'captcha-xxx'`
> fix: mock path

- packages/preset-umi/src/features/mock/getMockData.test.ts
- packages/preset-umi/src/features/mock/getMockData.ts
1、mock 文件忽略 `d.ts`
2、当 mock 文件夹下的文件没有导出 `default` 时应该被忽略，而不是报错终止
3、当 mock 重复定义时，给出日志提示，按先后加载的顺序覆盖，而不是报错终止。
存在一个定义被多个页面使用的情况，根据 block 的拆包，集成之后会有重复的定义项
> feat: mock ignore d.ts

- packages/plugins/src/layout.ts
可以在 layout 的 runtime 配置中使用 initialState 变量
```
export const layout = ({
initialState,
setInitialState,
}) => {
return {}
}
```
> feat: layout plugin runtime support initialState

- packages/plugins/src/layout.ts
修复 layout title 取值问题，项目中一般是
```
{
title: 'Ant Design Pro',
}
```
> fix: layout title

- packages/bundler-utils/src/index.ts
- packages/plugins/src/antd.ts
- packages/preset-umi/src/features/appData/appData.ts
- packages/preset-umi/src/features/esmi/esmi.ts
- packages/preset-umi/src/features/vite/vite.ts
- packages/preset-umi/src/index.ts
- packages/preset-umi/src/libs/scan.test.ts
- packages/preset-umi/src/libs/scan.ts
- packages/preset-umi/src/utils/transformIEAR.ts
修复 vite 及 ESMi 模式不兼容部分插件逻辑导致无法启动的问题，改动点：
1. 修复本地依赖扫描时部分依赖丢失的问题
2. 添加统一的 `isDepPath` 工具函数到 `bundler-utils`，判断是否是三方依赖和 monorepo 子包依赖
3. Vite 模式下强制禁用 `plugin-antd` 的 `babel-plugin-import`
4. 本地依赖扫描时排除 import type，避免 resolve 失败
5. 依赖扫描从『仅 ESMi 启用』变成『Vite 模式均启用』，解决 monorepo 子包依赖无法走 Vite 预编译的问题
> fix: deps scan in vite mode

- CONTRIBUTING.md
在CONTRIBUTING.md这个文件的注释与命令之间添加空格，提供可读性，例如：
```bash
$ a command
$ another command
```
> docs: provide readability

- .husky/commit-msg
- .husky/pre-commit
- scripts/verifyCommit.ts
修复了 husky 对 commit-msg 格式的校验。
1. husky v7 废弃了 `GIT_PARAMS` 和 `HUSKY_GIT_PARAMS`，取而代之应使用 `$1` 传递，详见 [Breaking changes](https://typicode.github.io/husky/#/?id=breaking-changes)
2. 兼容了命令行和 vscode scm 可视化提交两种报错信息的正确弹出：
<br>
<br>
> fix(husky): husky v7 commit msg verify

- examples/mfsu-independent/.gitignore
- examples/mfsu-independent/README.md
- examples/mfsu-independent/index.html
- examples/mfsu-independent/package.json
- examples/mfsu-independent/src/App.tsx
- examples/mfsu-independent/src/antd.tsx
- examples/mfsu-independent/src/framer-motion.tsx
- examples/mfsu-independent/src/index.tsx
- examples/mfsu-independent/tsconfig.json
- examples/mfsu-independent/webpack.config.js
- packages/bundler-esbuild/src/cli.ts
- packages/bundler-vite/src/cli.ts
- packages/bundler-webpack/src/cli.ts
- packages/mfsu/src/mfsu.ts
- packages/utils/src/index.ts
- packages/utils/src/tryPaths.ts
1. 尝试兼容了更多独立的 mfsu entry 配置方法，让对外使用者不容易踩坑
2. [`sorrycc/example-webpack-mfsu`](https://github.com/sorrycc/example-webpack-mfsu) 的 mfsu 版本旧了且一些使用姿势过时了，故把独立使用 mfsu 的 case 拿进来单独照顾
> feat(mfsu): mfsu without umi usage

- .gitignore
- packages/plugins/src/tailwindcss.ts
根据 https://github.com/umijs/umi-next/pull/281#discussion_r787745177 的建议将插件生成的临时样式文件写入 `api.paths.absTmpPath` 内。
> plugin(tailwindcss): Write generated css file into .umi folder

- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/Toc.tsx
1. 限制 TOC 的最大高度，避免章节太多导致 TOC 超出屏幕，超过的部分可上下滚动
2. 小屏场景下不显示 TOC
> feat(plugin-docs): Improved TOC

- packages/bundler-esbuild/src/build.ts
外部独立使用 mfsu + 采用 esbuild 打包第三方库时，类似自定义的 `process.env.*` 环境变量无法被替换，这里支持下用户自配置。
> feat(mfsu): support user define want replace env var

- packages/plugin-docs/client/theme-doc/Head.tsx
- packages/plugin-docs/client/theme-doc/LangSwitch.tsx
- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/Logo.tsx
- packages/plugin-docs/client/theme-doc/NavBar.tsx
- packages/plugin-docs/client/theme-doc/Search.tsx
- packages/plugin-docs/client/theme-doc/Sidebar.tsx
- packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx
- packages/plugin-docs/client/theme-doc/Toc.tsx
- packages/plugin-docs/client/theme-doc/tailwind.css
- packages/plugin-docs/tailwind.config.js
帮 `plugin-docs` 增加了暗黑模式：
启用逻辑：
- 若用户曾经访问过网站，会开启他上次选择的主题 (localstorage)
- 若用户不曾访问过网站，会开启他当前操作系统选择的主题 (prefers-color-scheme)
> feat(plugin-docs): Added dark mode

- packages/plugin-docs/client/theme-doc/components/Message.tsx
- packages/plugin-docs/client/theme-doc/index.ts
- packages/plugin-docs/src/index.ts
- packages/plugin-docs/tailwind.config.js
在 plugin-docs 加入了 Message 组件，使用方式：在 mdx 文件中加入
```tsx
import { Message } from 'umi';
```
即可使用 Message 组件。
> feat(plugin-docs): Added mdx Message component for docs

- packages/plugin-docs/client/theme-doc/Github.tsx
修复了 `plugin-docs` 中黑暗模式的 GitHub 图标颜色问题
> fix(plugin-docs): Fixed GitHub icon color in dark mode

- packages/plugin-docs/client/theme-doc/Toc.tsx
1. 修复了 plugin-docs 中 TOC 在标题有大写英文字母、空格或全形括号时会无法跳转的问题。
2. 修复了 plugin-docs 中 TOC 对多级标题没有区分样式的问题
> fix(plugin-docs): Fixed TOC link bug and nested headings style

- packages/plugin-docs/client/theme-doc/Toc.tsx
将 plugin-docs 中 TOC 的上下淡出效果移除，避免影响阅读。
上下淡出本来是想暗示用户可以滚动，避免内容太多的情况下用户不知道下面还有内容，
但如果要避免影响阅读的话可能要监听当前的滚动位置来动态调节淡出效果的透明度，
但刚刚试了一下 react 的 style 好像还不支持 maskImage 传入 linear-gradient 的值，
所以不太好实现，因此先将样式直接移除。
> fix(plugin-docs): Removed fadeout effect on TOC

- packages/plugin-docs/client/theme-doc/context.ts
- packages/plugin-docs/client/theme-doc/useLanguage.ts
修复了 `plugin-docs` 中如果 `theme.config.ts` 内没有设置 `i18n` 的话会报错的 bug
> fix(plugin-docs-lang): Fixed that i18n may be undefined bug

- packages/plugin-docs/client/theme-doc/LangSwitch.tsx
- packages/plugin-docs/client/theme-doc/useLanguage.ts
1. 如果 theme.config.js 的 i18n 只设置了两个语言，则右上角的语言选单会改为点击直接切换，不需要下拉选择
2. 修复了当切换语言时，若两个语言都是不是默认语言，会跳转到错误路径的问题
> feat(plugin-docs): Improved user experience in switching language

- examples/mfsu-independent/README.md
- examples/mfsu-independent/package.json
- examples/mfsu-independent/webpack.config.esbuild.js
- packages/bundler-webpack/src/config/config.ts
- packages/bundler-webpack/src/config/javaScriptRules.ts
- packages/bundler-webpack/src/dev.ts
- packages/bundler-webpack/src/esbuildHandler/autoCssModules.ts
- packages/bundler-webpack/src/index.ts
- packages/bundler-webpack/src/loader/esbuild.ts
- packages/bundler-webpack/src/swcPlugins/autoCSSModules.ts
- packages/bundler-webpack/src/types.ts
- packages/mfsu/src/babelPlugins/awaitImport/checkMatch.ts
- packages/mfsu/src/esbuildHandlers/autoExport.ts
- packages/mfsu/src/esbuildHandlers/awaitImport/index.ts
- packages/mfsu/src/mfsu.ts
- packages/utils/src/index.ts
- packages/utils/src/isStyleFile.ts
这个 pr 做了几件事：
1. 新增 esbuild 模式支持 source 的 transipiler
2. 为了支持 mfsu 和 auto css module，重写了 mfsu 的 babel plugin 和 auto css modules 的 esbuild 转换版本
3. 新增一个 esbuild 作为 transpiler (esbuild-loader) 对外部独立使用的 webpack config 例子
> feat(esbuild): support use esbuild transpiler with mfsu mode

- .gitattributes
忽略掉 预编译依赖 的语言识别，显示出仓库真正使用的编码语言占比。
> chore(lang-identify): ignore deps file language detect

- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/components/Announcement.tsx
- packages/plugin-docs/client/theme-doc/context.ts
- theme.config.ts
帮 plugin-docs 加入了 Announcement 组件：
点击右边的 `x` 可关闭组件，直到下一个新的 Announcement 出现。
在 `theme.config.ts` 加入设置
```ts
export default {
// ...
announcement: {
title: 'Umi4 即将推出!!!',
link: 'https://github.com/umijs/umi-next',
},
// ...
}
```
即可使用。
> feat(plugin-docs): Added announcement

- types.d.ts
修复了 plugin-docs 的 Hero 组件引入了 .svg 图示但没有 module declaration 造成的 tsc 编译失败
> fix(plugin-docs): Fixed build failed caused by no .svg module declaration

- examples/tmp-swcTranspiler-swc/.umirc.ts
- examples/tmp-swcTranspiler-swc/package.json
- examples/tmp-swcTranspiler-swc/pages/index.tsx
- packages/bundler-webpack/src/config/javaScriptRules.ts
- packages/bundler-webpack/src/dev.ts
- packages/bundler-webpack/src/loader/swc.ts
- packages/bundler-webpack/src/types.ts
- packages/preset-umi/package.json
- packages/preset-umi/src/features/polyfill/polyfill.ts
- packages/preset-umi/src/features/polyfill/swcPolyfill.ts
- packages/preset-umi/src/index.ts
这个 pr 做了几件事：
1. 支持 swc 按需取用 polyfill 
2. 改善了 swc 的配置
3. 在 swc 作为 transpiler 场景自动关闭 mfsu，因为他们不兼容
这将在基础 polyfill 大小上获取 80kb 左右的收益：
同时提升 x1.5 - x2 的编译速度 （无缓存测试，但 babel 场景默认 preset 导入了更多的 polyfill 会增加处理代码量）：
> chore(swc): improve swc loader polyfill

- packages/bundler-webpack/src/config/javaScriptRules.ts
- packages/bundler-webpack/src/swcPlugins/autoCSSModules.ts
- packages/bundler-webpack/src/swcPlugins/autoCssModules.test.ts
解决在 `examples` 之外，单独使用 `umi` 时（即正常的开发者使用场景），使用 `swc` 作为 transpiler ，auto css 插件 visit 遍历访问语法树会报错的问题。
1. 限制收窄 visit 的访问场景仅限于需要处理的部分，即 import declare （ eg. `import styles from './index.less'` ）
2. 不考虑 `await import('./index.less')` 的场景，没有必要
> fix(swc): auto css plugin visit js file error

- packages/bundler-esbuild/src/plugins/aliasLessImportPath.test.ts
- packages/bundler-esbuild/src/plugins/less.ts
1. 修复 esbuild mfsu 导入依赖中的 `.less` 文件，路径定位错的问题。
2. 修复导入带 `@scope` 的包时，`alias` 逻辑匹配前缀的问题：
比如 `@scope/pkg` 不应该受到 `@` 的 `alias` 影响。
case：
```ts
import '@arco-design/web-react/dist/css/index.less'
import 'antd/dist/antd.less'
```
> fix(esbuild): less plugin cannot import style file from deps

- packages/bundler-webpack/src/config/javaScriptRules.ts
- packages/bundler-webpack/src/loader/swc.ts
- packages/bundler-webpack/src/types.ts
- packages/preset-umi/src/features/polyfill/polyfill.ts
- packages/preset-umi/src/index.ts
取消了 swc 的自动 polyfill 机制，改为一致使用 entry 策略生成的 polyfill 导入。
1. **es2022 不支持**：受 #335 启发，尝试未正式发布的 es2022 特性（如 `array.at`），发现无论使用哪种 swc 提供的 polyfill 策略（`usage` / `entry`），都无法提供 es2022 的 polyfill （其中 `entry` 策略最多提供至 es2021 ）
2. **polyfill 查询列表已过时**：swc 的策略是自己维护了一份 `core-js-compat` 的 `modules-by-versions.json` 列表（已过时），无法即时同步上游 `core-js` 的最新 polyfill 变动
3. **未积极维护**：swc 长时间未积极维护 polyfill 功能模块
Refer:
https://github.com/swc-project/swc/issues/2607
https://github.com/swc-project/swc/issues/1604
综上情况，目前不应使用任何 swc 的 polyfill 提供策略，一致使用 babel 生成解 polyfill 问题。
使用 swc 的 `env.include` 也可解该问题，其实现与当前 babel 生成 polyfill 大致相同，可见于我的 [swc polyfill 解法](https://blog.csdn.net/qq_21567385/article/details/122844920) 一文。
> chore(swc): remove swc auto polyfill

- .github/workflows/ci.yml
这两次 commit 的 ci 中， **macos** 的 post cache 都超时挂了：
https://github.com/umijs/umi-next/runs/5143960840?check_suite_focus=true
https://github.com/umijs/umi-next/runs/5141916853?check_suite_focus=true
用 pnpm 官方给的示范（ [pnpm/action-setup](https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time) ），升级下版本来解决问题
> ci: upgrade cache actions version and use pnpm setup

- packages/bundler-webpack/src/config/detectDeadCode.ts
修复 deadCodePlugin 中，使用 TS any 的问题。
相关 PR: https://github.com/webpack/webpack/pull/15387
> feat(bundler-webpack): fix any type

- packages/bundler-webpack/src/dev.ts
- packages/bundler-webpack/src/requireHook.ts
1. 修复 requireHook.ts webpack deepImports name 获取有问题导致三方插件使用有问题
2. dev 模式未传 babelPreset 导致无法覆盖默认的 babelPreset
> feat(bundler-webpack): dev missing babelPreset

- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/Toc.tsx
- packages/plugin-docs/client/theme-doc/context.ts
- packages/plugin-docs/package.json
- theme.config.ts
帮 plugin-docs 的 theme-doc 加入了 HTML title。
> fix(plugin-docs): Added HTML title

- package.json
1. **`packageManager` 标准化**：该字段的标准格式是 `name@version` ，可以看到 vscode 默认有虚线提示，且单独使用 `name` 是不被 `turborepo` 等社区工具识别的。
2. **限制开发时本地 `pnpm` 最小版本**：为了解 `peerDependencies` 和开发环境多实例寻址问题，以后可能需要 `dependenciesMeta` 来解，其要求的最小版本要 >=6.20 （[详见这里](https://pnpm.io/package_json#dependenciesmeta)），这里向后兼容
3. **限制开发时本地 node 最小版本**
> chore(env): ensure pnpm and node min version

- packages/preset-umi/src/commands/build.ts
产物对 `umi` 的正则识别有问题，需要兼容 `umi.js` 和 `umi.*.js` 格式。
> fix(build): identify umi output assets reg match

- examples/with-tailwindcss/package.json
将 `@umijs/plugins` 的版本升级到 `4.0.0-rc.2`，解决 example 启动报错。
> dep: update @umijs/plugins to 4.0.0-rc.2

- packages/bundler-webpack/package.json
- packages/bundler-webpack/src/config/compressPlugin.ts
- packages/bundler-webpack/src/plugins/ParcelCSSMinifyPlugin.ts
- packages/bundler-webpack/src/plugins/ParcelCssMinifyPlugin.ts
- packages/bundler-webpack/src/schema.ts
- packages/bundler-webpack/src/types.ts
可以预料到  parcel css 可以用来做 css 产物压缩。
实现这个功能。
可以看到 parcel 更聪明：
速度上两者差不多。
> feat(css-minify): support use `@parcel/css` minify css output

- packages/plugin-docs/client/theme-doc/components/Message.tsx
- packages/plugin-docs/client/theme-doc/tailwind.css
写文档的过程中发现 `plugin-docs` 中的 `<Message />` 组件样式有点问题，因此进行修复：
1. 修复了组件中的文字样式被 `article > p` 影响导致带有 `margin-top` 的问题
2. 修复了组件有 emoji 时，emoji 和文字会出现在不同行的问题
修复后的样式：
> feat(plugin-docs): Improved <Message /> component styles

- packages/mfsu/src/babelPlugins/awaitImport/getAliasedPath.test.ts
- packages/mfsu/src/babelPlugins/awaitImport/getAliasedPath.ts
主要为了解决：
```js
alias: {
'react': 'some.js'
}
```
会匹配到 `react-dom` 类型的问题：
```js
import 'react-dom'
// -> import 'some.js-dom' 😭
```
> fix(mfsu): esbuild alias match

- packages/plugin-docs/client/theme-doc/LangSwitch.tsx
- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/Logo.tsx
- packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx
- packages/plugin-docs/client/theme-doc/Toc.tsx
- packages/plugin-docs/client/theme-doc/components/Message.tsx
- packages/plugin-docs/client/theme-doc/firefox-polyfill.css
- packages/plugin-docs/client/theme-doc/tailwind.css
文档的 Message 组件在夜间模式下的颜色表现出现了一些问题，这源于 `.dark article p` 的样式覆盖了它预期的样式。在此 PR 中修复了这个问题。
除此之外，此 PR 还做了这些事情：
- 适配了 Message 组件的 `info`, `success`, `warning` 和 `error` 样式。[check](https://github.com/umijs/umi-next/pull/402/files#diff-44bee362b0587d23f89199098f0eb298691b4b43ff8efe840f66358180db87acR160-R198)
- 当文档的 Toc 高度未超出 `max-height` 时，不再显示 y 轴的滚动条。[check](https://github.com/umijs/umi-next/pull/402/files#diff-de7a15c3c1f187cd22648a21c9c3670ddb8cbc02fa4fc8af81c63775d2699e98L43-R43)
- 优化切换主题模式按钮在日间模式的背景颜色。[check](https://github.com/umijs/umi-next/pull/402/files#diff-cc6ba0b692ab5909a17148d509a4341a308cfc860113fad0028cf1e552071ea4L41-R41)
- 水平居中对齐切换语言按钮文本内容。[check](https://github.com/umijs/umi-next/pull/402/files#diff-bc731492b883fc938b1c69e564f42cd9c5df36bd475728b705b66aa81dd7aa31L28-R28)
- …
> fix(plugin-docs): fix color behavior of Message component

- packages/plugins/src/antd.ts
antd 配置变更，antd:config 修改为 antd:configProvider
```
AssertionError [ERR_ASSERTION]: Invalid config values: antd
Invalid value for antd:
"config" is not allowed
```
> fix: antd:config is not allowed

- packages/plugin-docs/client/theme-doc/LangSwitch.tsx
- packages/plugin-docs/client/theme-doc/useLanguage.ts
对 `plugin-docs` 的 `theme-doc` 做了小改进：
当用户切换语言后，会将语言保存在 local storage 中，
下次访问网站时，若路由输入的是默认语言，会自动切换到上次选择的语言中。
这个避免了每次用网址访问 https://next.umijs.org 都会跳回默认语言的问题。
> fix(plugin-docs): Remember user language setting in localstorage

- docs/docs/tutorials/getting-started.md
no more  `bpm` in code
```
$git grep -il bpm
examples/bundler-vite-demo/src/logo.svg
packages/bundler-webpack/compiled/webpack-bundle-analyzer/public/viewer.js.map
pnpm-lock.yaml
```
> chore(docs): ✏️ no more Bpm typo

- packages/plugins/src/tailwindcss.ts
**问题：** 在使用 tailwindcss 插件时，build 构建完成会处于等待状态，这是因为 tailwindcss 子进程仍在进行中
**处理：** 监听 onBuildComplete 关闭 tailwindcss 子进程
**相关issue:**  #434
> fix(plugins): tailwindcss child process  not exit

- packages/preset-umi/templates/generate/page/index.tsx.tpl
在使用 generate page 中发现页面模板中的 less 路径使用了 name 作为名称，这将是错误的路径，修改为 index
> fix(preset-umi): page template styles path error

- packages/plugin-docs/client/theme-doc/Search.tsx
修复了 `plugin-docs` 的 `theme-doc` 中的两个问题：
Before
After
Before
After
> fix(plugin-docs): Fix doc-theme search input bugs

- packages/preset-umi/src/features/apiRoute/apiRoute.ts
若用户启用了 API 路由功能，且设置了部署平台为 Vercel，则检查工作目录下是否有 `vercel.json` 文件，没有的话自动生成一个。避免用户部署上去以后由于没有 `vercel.json` 中设置的 `ENABLE_FILE_SYSTEM_API: "1` 导致 API 路由不生效。
> feat(api-routes-vercel): Check there is `vercel.json` if user want to use API routes in Vercel

- packages/preset-umi/src/features/apiRoute/apiRoute.ts
修复了由于在 `api.onBeforeCompiler` 启用了监听导致 `umi build` 无法顺利结束进程的问题
> fix(api-routes): Fix `watch` in api-route causing `umi build` cannot exit

- packages/preset-umi/src/commands/dev/dev.ts
将 `RouteMiddleware` 挪到最后，以便插件有时机在 `CompileMiddleware` 和 `RouteMiddleware` 中间做请求处理
> refactor(preset-umi): move route middleware to the back

- packages/core/src/service/generator.ts
- packages/preset-umi/src/commands/generate/page.test.ts
- packages/preset-umi/src/commands/generate/page.ts
- packages/preset-umi/templates/generate/page/index.tsx.tpl
- packages/utils/src/BaseGenerator/BaseGenerator.test.ts
- packages/utils/src/BaseGenerator/BaseGenerator.ts
```bash
$npx umi g page  foo/bar
info  - @local
Write: pages/foo/bar.tsx
Write: pages/foo/bar.less
```
```bash
$npx umi g page  xxx/yyy --dir
info  - @local
Write: pages/xxx/yyy/index.less
Write: pages/xxx/yyy/index.tsx
```
> feat: umi generate page support nested folder and  --dir option

- .gitignore
- examples/with-react-query/package.json
- examples/with-react-three-fiber/package.json
- jest.config.ts
- package.json
- packages/ast/package.json
- packages/ast/src/setConfigByName/setConfigByName.test.ts
- packages/babel-preset-umi/package.json
- packages/bundler-esbuild/package.json
- packages/bundler-vite/package.json
- packages/bundler-webpack/package.json
- packages/core/package.json
- packages/create-umi/package.json
- packages/mfsu/package.json
- packages/plugin-docs/package.json
- packages/plugins/package.json
- packages/preset-umi/package.json
- packages/utils/package.json
- scripts/checkPackageFiles.ts
- scripts/turbo.ts
- turbo.json
---
before: https://github.com/umijs/umi-next/runs/5491529285?check_suite_focus=true
after: https://github.com/umijs/umi-next/runs/5491619959?check_suite_focus=true
---
1. 把 `test` 命令拆解到子包里，此时：
i. 子包 `src` 里面没有 `*.test.ts` 的不添加 `test` script，否则在子包里运行找不到任何测试文件会报错，为了保证成立，使用 `scripts/checkPackageFiles.ts` 来做自动校验和添加 script
ii. 变更 `jest.config.ts` 中配置，变成针对每个子项目的匹配模式
2. 使用 `turbo` 跑 test 命令，为了实现缓存：把 jest 缓存放到子包里（`.gitignore` 忽略掉该缓存目录），然后 `turbo` 来缓存 jest 的缓存，这样只要代码 hash 不变，上次的 jest 缓存就会自动复活
> ci: use turbo run test

- packages/preset-umi/src/features/apiRoute/dev-server/esbuild.ts
- packages/preset-umi/src/features/apiRoute/vercel/esbuild.ts
1. 修复了 API 路由打包时没有指定 `platform: 'node'` 导致部分依赖无法使用的问题
2. 修复了 API 路由的 Vercel Adpater 原本以 `esm` 格式打包导致部分不支持 `esm` 的依赖会报错的问题
> fix(api-route): Fix bug of build platform and format

- packages/plugins/src/unocss.ts
修复build不会退出的情况，只有在 dev 下才开启 watch
@unocss/cli [generate](https://github.com/unocss/unocss/blob/main/packages/cli/src/index.ts#L20) 不支持创建路径不存在的文件夹，outputPath 中 暂时没有加 plugin-unocss
> fix(plugin-unocss): fix build don't exit

- .github/workflows/ci.yml
没限制 push 的 ci 分支，PR 里双倍的跑，头要炸了
现在三种时候会跑 ci ：
1. commit 到了主分支 `master` 会跑 ci
2. PR 的时候会跑，在任意仓库提过来的 PR 都会跑
3. fork 的仓库的默认分支可以手动跑 ci （一般情况是 master，如果不是，就切成默认分支，就可以手动运行）
> ci: only run on `master` branch

- .gitignore
- packages/preset-umi/src/features/apiRoute/constants.ts
- packages/preset-umi/src/features/apiRoute/vercel/esbuild.ts
这几天在开发及部署 [umijs/umi-blog-example](https://github.com/umijs/umi-blog-example) 到 [Vercel](https://vercel.com/dashboard) 时发现了 API 路由功能还存在许多问题，距离投入生产还有一段距离，目前正在努力修复中，这个 PR 修复了两个已经找到的问题：
也就是说，虽然启用了 Vercel 的 [File System API](https://vercel.com/docs/file-system-api)，但我们不自己生成最终产物 (`.output`)，而是在 `umi build` 过程中才生成 `api` 目录，然后因为开启了 File System API ，所以 Vercel 还是会帮忙把这个产物编译到 `.output` 中。
在开发 [umijs/umi-blog-example](https://github.com/umijs/umi-blog-example) 时因为用了 [Prisma](https://www.prisma.io/) 作为 ORM，发现这个包会在运行时读取自己目录下的文件，而因为他的代码被我们打包起来了，所以这个文件自然就找不到了 ...
现在我们不打包这些依赖，Vercel 会帮我们在 Serverless function 运行时放到他的 `node_modules` 里面。
> fix(api-route): Fix bugs of Vercel adapter

- packages/bundler-vite/package.json
修复 bundler-vite scripts 没发布到 NPM，导致 postinstall 脚本执行失败的问题
> fix(bundler-vite): scripts not found in dist

- packages/preset-umi/src/commands/generators/page.test.ts
- packages/preset-umi/src/commands/generators/page.ts
fix: 通过 prompts 获取 page name 之后未 调用 setPath 导致 page 文件名未分析和路径错误
feat: 增加通过 prompts 让用户选择 是否 `--dir` 
test: 增加对应测试
> 修复 umi  g  page 在交互模式下生成页面的bug

- docs/blog/mfsu-independent-usage.md
补充下 mfsu 独立使用的方法文档。
我做了一个 cra 接入 MFSU 的实例 [repo](https://github.com/fz6m/cra-with-mfsu)，目前是放在我名下的，要不要作为 umijs 的一个分支存放？（或者放在 umijs organization 里）因为他的依赖实在太多了，而且比较重视某一次的 commit change ，放在 `examples/*` 下面不好。
> docs: mfsu supplement

- packages/core/src/service/plugin.ts
- packages/umi/package.json
- packages/utils/src/register.ts
for issue  #504 
1. umi `engins.node`  >= 14 进 `package.json` js 直接写插件的不会因为 es 问题，导致无法执行。（参考  https://node.green/
2. 改进 register 移除没有必要的`includes`判断，pirates 已经会ext分发
3. 支持指定 ext 是否需要transform
4. 保留 require.cache
```
$time  node   /Users/pshu/git/umi-next/packages/umi/bin/umi.js  g page test/test --dir
info  - @local
Write: index.less
Write: index.tsx
real	0m1.150s
user	0m1.057s
sys	0m0.165s
```
> performace improve for umi cli

- packages/bundler-vite/scripts/linkDeps.js
修复 yarn 安装时 bundler-vite 的 postinstall 脚本执行失败的问题
> fix(bundler-vite): install failed bug with yarn

- packages/preset-umi/src/index.ts
- packages/umi/index.d.ts
如果在项目中使用 `pnpm i umi` 然后使用 API 路由功能，无法透过
```ts
import { UmiApiRequest, UmiApiResponse } from "umi";
```
启用 Typescript 的类型支持。
使用 `import { UmiApiRequest, UmiApiResponse } from "umi";` 的时候，IDE 会去 `node_modules/umi/index.d.ts` 查找类型，但这个文件是这样写的：
```ts
export type {
IRoute,
UmiApiRequest,
UmiApiResponse,
} from '@umijs/preset-umi/src/types';
```
可以看到我们要的类型是从 `@umijs/preset-umi/src/types` 导入的，但 `src` 目录并不会在 `pnpm i` 的时候下载下来。
让这些类型透过 `@umijs/preset-umi` 导出，而不是从 `@umijs/preset-umi/src/types`
> fix(api-route-types): Fix types of api route exported from preset-umi

- packages/bundler-webpack/package.json
- packages/preset-umi/src/commands/build.ts
- packages/preset-umi/src/commands/dev/dev.ts
- packages/preset-umi/src/utils/lazyImportFromCurrentPkg.ts
- pnpm-lock.yaml
1. 用了，但是没把 `@umijs/bundler-utils` 放到生产依赖里。
2. require 的时候要走绝对路径，不然跑到其他地方了。
try resolve https://github.com/umijs/umi-next/issues/480
> fix: missing dep and require abs path

- packages/bundler-webpack/src/client/client.ts
https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/webpackHotDevClient/webpackHotDevClient.ts#L156
之前的版本是支持 SOCKET_SERVER 的配置的， 参考之前的代码做了修改。
> feat(bundler-webpack): ws client host support process.env

- packages/mfsu/src/dep/dep.ts
`swiper/react` 不能使用的错误是因为无法解析到正确的文件地址，只要添加 enhanced-resolve `exportsFields: ['exports'], ` 即可修复，
`swr` 开启 exportsFields 之后，无法解析路径，是因为没有配置对应的 conditionNames，配置之后就可以使用了。
至于配置的 conditonName 的放置的位置没有必要纠结。
参考  https://github.com/webpack/enhanced-resolve/issues/318#issuecomment-1055518577 
和
https://github.com/webpack/enhanced-resolve/blob/c960801d5cfbb6a472e40a7fe8f6c0679955a13b/lib/util/entrypoints.js#L470 （conditonNames 只是 resolve 是否可以使用的集合）
> 🐛  fix file reslove in module with exports definition

- packages/core/src/service/generator.ts
- packages/create-umi/src/index.ts
- packages/preset-umi/src/commands/generators/api.ts
- packages/preset-umi/src/commands/generators/component.ts
- packages/preset-umi/src/commands/generators/mock.ts
- packages/preset-umi/src/commands/generators/tailwindcss.ts
cli args 参数以及去掉了node和 bin 信息（ https://github.com/umijs/umi-next/blob/1ee72d41008d425d6d2001d439d8fbac576cebe9/packages/create-umi/src/cli.ts#L5 ），最后取值的时候就直接使用第一个参数即可
配合 src 目录 和 新增 layouts  和 components 
对应 ts定义 去掉 optional
> cerate-umi 和 生成器 bug fix

- packages/lint/src/index.ts
之前操作了同一个 args 对象，导致 eslint/stylelint 的 args 出现冲突
> fix(lint): args conflict between eslint & stylelint

- packages/lint/compiled/@rushstack/eslint-patch/LICENSE
- packages/lint/compiled/@rushstack/eslint-patch/lib/modern-module-resolution.js
- packages/lint/compiled/@rushstack/eslint-patch/package.json
- packages/lint/package.json
- packages/lint/src/config/eslint/setup.ts
- pnpm-lock.yaml
解决 `umi`、`@umijs/max`、`bigfish` 包裹导出 `@umijs/lint` 配置时，无法从 `@umijs/lint` 寻找插件依赖的问题，解法：
1. 预打包 `@rushstack/eslint-patch`，包比较特殊无法走脚本，目前是手动复制的
2. 修改 `@rushstack/eslint-patch` 的产物中的解析逻辑，部分插件从 `@umijs/lint` 开始 resolve，diff：https://github.com/umijs/umi-next/commit/7280a75bfbacc044fd7172fab57ed9297dd78a19
> feat(lint): use forked eslint-patch

- examples/bigfish/.umirc.ts
- examples/bigfish/tsconfig.json
- packages/preset-umi/src/features/configPlugins/configPlugins.ts
- packages/preset-umi/src/features/vite/vite.ts
- packages/preset-umi/src/registerMethods.ts
- packages/preset-umi/src/utils/transformIEAR.test.ts
- packages/preset-umi/src/utils/transformIEAR.ts
处理因为 @fs 导致的 ts 声明失效问题
- @fs 仅针对 vite 模式开启
- @fs 依赖的三方路径绝对路径会转为相对路径
- @fs 的alias 移动到 feature/vite.ts 中
> feat(preset-umi): handle ts prompt problems caused by @fs

- examples/bigfish/app.ts
- examples/bigfish/pages/users.tsx
- packages/plugins/src/request.ts
重构了 request 插件：
1、为 request 方法添加了 typescript 泛型。
2、重新增加了构建时配置中的 dataField 来满足 useRequest 的需要
3、去除了内置的错误处理机制。更改为通过在运行时配置中配置 errorThrower 和 errorHandler 来进行统一的错误管理。并且会在文档中给出样例，该样例就是 umi3 的 request 内置错误处理机制。
> fix: plugin-request

- packages/plugins/src/antd.ts
antd 插件的 `runtime.tsx` 增加 react 引入，以支持 react 17 以下的版本
> fix(plugins): antd plugin support react 17-

- packages/plugin-docs/client/theme-doc/Head.tsx
- packages/plugin-docs/client/theme-doc/Logo.tsx
- packages/plugin-docs/client/theme-doc/context.ts
为 `plugin-docs` 增加了透过配置文件 `theme.config.ts` 对顶部导航栏进行自定义扩展的能力。
```ts
// theme.config.ts
import MyCustomLogo from '@components/MyCustomLogo';
export default {
logo: MyCustomLogo
};
```
```ts
// theme.config.ts
import VersionSwitch from '@components/VersionSwitch';
export default {
leftNavComponents: [ VersionSwitch ]
};
```
```ts
// theme.config.ts
import VersionSwitch from '@components/VersionSwitch';
export default {
rightNavComponents: [ VersionSwitch ]
};
```
> feat(plugin-docs): Add configs for customize head of plugin-docs

- packages/core/src/service/service.ts
- packages/preset-umi/src/features/check/check.ts
- packages/preset-umi/src/features/transform/CodeFrameError.ts
- packages/preset-umi/src/features/transform/transform.ts
- packages/preset-umi/src/types.ts
改进 `onCheckCode` hook，便于开发者抛出精确到行列的错误信息给用户（如 Bigfish 强约束）：
1. `onCheckCode` hook 改为同步模式，使得检查中抛出的错误可以同时在 webpack 的 compiletime 和 runtime 展示，并且阻断编译
2. `onCheckCode` 参数增加 `CodeFrameError`，抛出该错误可以实现精确到行列的报错，对用户更友好，同时也兜底支持原生 `Error`
用法：
```ts
api.onCheckCode({ CodeFrameError, ...args }) {
args.imports.forEach(({ source, loc }) => {
if (source xxx) throw new CodeFrameError('balabala', loc);
});
}
```
其他相关修改：
1. `event` 类型的插件 Hook 支持同步模式，`applyPlugins` 时传递 `sync: true` 即可切换并获得正确的类型
2. check.ts 中对类似 `_@ant-design_icons@4.7.0@ant-design/icons` 引入的检测改为 `CodeFrameError`
示例效果：
> feat(preset-umi): better onCheckCode

- packages/plugin-docs/client/theme-doc/Head.tsx
- packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx
- packages/plugin-docs/client/theme-doc/context.ts
- theme.config.ts
在 `plugin-docs` 的 `themeConfig` 增加了 `themeSwitch` 配置项，当 `themeSwitch` 为 `false` 时，顶部导航栏右边就不会显示主题切换开关。
> feat(plugin-docs): Add theme config for hide the theme switch

- docs/docs/api/plugin-api.md
- packages/preset-umi/src/features/transform/babelPlugin.test.ts
- packages/preset-umi/src/features/transform/babelPlugin.ts
- packages/preset-umi/src/types.ts
onCheckCode 的 specifiers 信息添加 babel 的 `importKind`，用于判读引入类型
> feat(preset-umi): add kind for onCheckCode import specifiers

- packages/plugin-docs/src/compiler.ts
修复了 #644 问题 - `plugin-docs` 点击 TOC 会导致页面陷入加载循环的问题。
问题原因是当前 `useLocation` 会依赖 `window.location` 对象，导致 `window.location.hash` 发生变化时，触发了页面组件的重新加载，而页面组件内有 `useEffect` 会重新设置 `window.location.hash` (为了让带着 hash 进入文档的用户可以定位到对应的位置），结果重新设置的结果导致了页面组件又重新加载了，陷入死循环。
> fix(plugin-docs): Fix #644 TOC link makes page reload loop

- packages/plugin-docs/client/theme-doc/tailwind.css
- packages/plugin-docs/src/compiler.ts
本 PR 针对 `@umijs/plugin-docs` 插件做了如下工作：
- 添加代码块**行高亮**支持，配置行高亮样式。
- 添加代码块**文字高亮**支持，配置文字高亮样式。
- 添加代码块**语言**支持。
- 添加代码块**行号**支持。
- 配置代码块**标题**样式。
- 修复夜间模式下链接和行内代码链接的样式。
<details>
<summary>渲染编写的代码如下</summary>
```md
编写一个**默认导出**的函数：
```ts /user/ {2,7} title="最简单的 Model"
// src/models/useUser.ts
export default () => {
const user = {
username: 'umi',
};
return { user };
};
```
```
</details>
已知的问题：
- 当代码块横向滚动时，代码块的语言不会随着滚动（无法固定在代码块的右上方）。
> feat(plugin-docs): add support for line highlight and word highlight

- docs/docs/api/runtime-config.md
- packages/plugin-docs/client/theme-doc/Toc.tsx
修复了 #645 在 `plugin-docs` 文档中使用大括号 `{` `}` 会导致 mdx 误判导致编译报错的问题
> fix(plugin-docs): Fix #645 mdx error if there is brackets in docs

- packages/plugin-docs/client/theme-doc/NavBar.tsx
- packages/plugin-docs/client/theme-doc/context.ts
帮 `plugin-docs` 新增了从 `theme.config.ts` 配置文件为顶部导航栏增加下拉选单（二级导航）的能力。
```ts
// theme.config.ts
export default {
// ...
navs: [
{
path: '/docs',
title: 'Docs',
type: 'nav',
dropdown: [
{ title: 'Tutorials', path: '/docs/tutorials/getting-started' }
],
children: [ /* ... */ ]
}],
// ...
};
```
> feat(plugin-docs): Add dropdown for nav items

- packages/plugin-docs/src/compiler.ts
修复了在 `plugin-docs` 不同文档页面切换时，不会滚动到页面顶部的问题
> fix(plugin-docs): Fix bug that not scroll to top when route change

- packages/umi/src/pluginUtils.ts
修复 `htttp-proxy-middleware` 的导出，该包没有 default 导出，之前的方式会 undefined
> fix(umi): correct export for http-proxy-middleware

- packages/plugin-docs/client/theme-doc/Search.tsx
帮 plugin-docs 的搜索框加入了 id 属性，可以用全局样式对其进行覆盖。
`search-input-wrapper` 是整个搜索框组件
`search-results-wrapper` 是搜索后下方弹出的搜索结果的容器
> feat(plugin-docs): Add id attribute of search input component for style override

- packages/plugins/src/access.ts
- packages/plugins/src/initial-state.ts
1. 修复 initial-state 的 provider 顺序导致的 access 初始化值为空的 bug
2. 允许开启 access 但不创建 `src/access.ts`
> fix(plugins): access plugin initial state

- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/Logo.tsx
帮 plugin-docs 加入了页面容器的 id 属性，并且能够感知是否为首页
帮顶部导航栏的 title 加入了 id 属性
> feat(plugin-docs): Add id attribute of page container and header title

- packages/plugin-docs/client/theme-doc/Search.tsx
> feat(plugin-docs): Hide search hot key if not enabled in theme config

- packages/plugin-docs/client/theme-doc/Search.tsx
- packages/plugin-docs/client/theme-doc/Toc.tsx
- packages/plugin-docs/client/theme-doc/utils/getLinkFromTitle.ts
修复了 `plugin-docs` 搜索功能的几个问题：
Before
After
Before
After
> fix(plugin-docs): Fix plugin search cannot find level 3 title bug

- packages/plugin-docs/client/theme-doc/components/Features.tsx
修复了 `plugin-docs` 因为 Mac 系统约定当外接鼠标时会保持显示滚动条，导致宽度变窄而出现横向滚动条的问题。
> fix(plugin-docs): Fix home page horizontal scroll bar bug

- packages/plugin-docs/client/theme-doc/LangSwitch.tsx
- packages/plugin-docs/client/theme-doc/Layout.tsx
- packages/plugin-docs/client/theme-doc/Search.tsx
- packages/plugin-docs/client/theme-doc/components/Announcement.tsx
- packages/plugin-docs/client/theme-doc/firefox-polyfill.css
- packages/plugin-docs/client/theme-doc/useLanguage.ts
1. 修复了 Firefox 的毛玻璃补丁在没有 Announcement 组件时错位的问题
2. 优化搜索体验：点击搜索结果后关闭下拉选单
3. 增加了默认语言的支持，让不使用多语言的用户也能自定义默认显示的文字
> fix(plugin-docs): Fix firefox glossy background polyfill bug and add default locale

- tsconfig.base.json
umi 对 node 版本的要求为 14或以上。 结合这个网站 https://node.green/ ，可以发现 node14 及以上对 es 最新语法已经支持到了 es2019。
可以适当调整 target 值，以减少构建的包大小。
> build: 将 target 升到 es2019

- packages/plugins/libs/qiankun/master/common.ts
- packages/plugins/libs/qiankun/master/getMicroAppRouteComponent.tsx.tpl
- packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
- packages/plugins/src/layout.ts
- packages/plugins/src/qiankun/master.ts
1. 目前 `patchClientRoutes` 的路由缺少 context，在 qiankun 内避免使用 `useRouteData`
2. layout 插件侧边栏兼容通配符的路由路径
> fix(plugins): to avoid use route data in qiankun

- packages/plugin-docs/src/compiler.ts
修复当带着哈希值进入文档页面时，Chrome 浏览器无法自动滚动到对应位置的问题
> fix(plugin-docs): Fix hash anchor bug in Chrome

- packages/core/src/index.ts
- packages/core/src/service/generatePlugin.ts
- packages/core/src/service/generator.ts
- packages/core/src/service/pluginAPI.ts
- packages/preset-umi/src/commands/generators/api.ts
- packages/preset-umi/src/commands/generators/dva.ts
- packages/preset-umi/src/commands/generators/jest.ts
- packages/preset-umi/src/commands/generators/prettier.ts
- packages/preset-umi/src/commands/generators/tailwindcss.ts
- packages/preset-umi/src/commands/generators/tsconfig.ts
```bash
(ins)$u g jest
info  - @local
✔ Will you use @testing-library/react for UI testing?! … no
info  - Write package.json
warn  - scripts.test already exists, skip update
info  - Write jest.config.ts
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
info  - Install dependencies with pnpm
(ins)$u g jest
info  - @local
warn  - jest has already enabled. You can remove jest.config.{ts,js}, then run this again to re-setup.
```
> Fix/ make generator disabled error message

- packages/core/src/service/generatePlugin.ts
- packages/core/src/service/generator.ts
- packages/preset-umi/src/commands/generators/dva.ts
- packages/preset-umi/src/commands/generators/tailwindcss.ts
注册 generator 的时候  api.appData.mainConfigFile 还是 undefined，所以有变量引用的 字符串需要 函数包下延迟执行
> fix: 🚑   api.appData.mainConfiFile is undefined when register generator

- packages/plugins/src/qiankun.ts
- packages/plugins/src/qiankun/master.ts
qiankun 插件配置项增加 `externalQiankun`，控制 qiankun 依赖是否以绝对路径引入，解 qiankun external 不生效的问题。
ref: #744
> fix(plugins): allow control import for qiankun external

- docs/docs/api/api.md
- packages/create-umi/templates/app/.gitignore.tpl
- packages/preset-umi/src/features/terminal/terminal.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
可能的风险是，已经生成的 plugin-terminal 会和 core/terminal.ts 
需要用户手动删除 .umi 文件夹 解决。
> Feat/terminal move to .umi/core/terminal.ts

- examples/ant-design-pro/config/config.ts
- examples/ant-design-pro/package.json
- examples/boilerplate/.umirc.ts
- examples/boilerplate/components/404/index.tsx
- packages/preset-umi/src/features/tmpFiles/routes.ts
- pnpm-lock.yaml
- 修复当 component  是目录时, 直接加 ext 导致 not found
- 修复 examples `ant-design-pro`  gg-editor  版本不对导致的 页面显示异常
- ant-design-pro，boilerplate 增加用例测试 routes file 增加后缀
> fix(preset-umi): routes suffix read exception

- .umirc.ts
- packages/plugin-docs/client/theme-doc/Sidebar.tsx
- packages/preset-umi/src/features/routePrefetch/routePrefetch.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/umi.tpl
- packages/renderer-react/src/browser.tsx
1. 修复了在设置了 `publicPath` 或 `runtimePublicPath` 下，路由组件预加载的路径问题。
2. 如果用户配置了 `publicPath` ，这个路径会被加入到 `asset-manifest.json` 文件中所有资源的路径前面，因此运行时动态加载不需要做额外处理。但在打包时要把 `asset-manifest.json` 注入 `umi.js` 前面的时候，需要将 `umi.js` 文件名开头的 `publicPath` 给移除。
3. 如果用户配置了 `runtimePublicPath`，则运行时动态加载路由组件时要把 manifest 中静态资源路径开头的 `publicPath` 替换为 `window.publicPath`。
4. 修复了可能会把 manifest 注入到 umi.css 而不是 umi.js 的问题
5. 在 umi 官网启用了 route prefetch
> fix(route-prefetch): support publicPath and runtimePublicPath

- packages/preset-umi/src/features/tmpFiles/routes.ts
- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
- packages/preset-umi/templates/plugin.tpl
- packages/umi/client/client/plugin.js
- packages/umi/package.json
- packages/umi/src/client/plugin.ts
1. 防止 `layouts` 的本地文件全路径泄露到产物里，做个 alias 替换掉 prefix 。
2. 防止 client plugins 里的 `file` 字段里本地文件全路径泄露到产物里，由于没有强依赖这个路径，生产环境直接 `undefined` 。
> chore: avoid local path mix in outputs

- packages/renderer-vue/src/routes.ts
之前实现时缺省了 其它参数, 补齐下
主要用于路由配置meta 之类的需要, 可以通过 `useRoute` 获取 或者一些别的操作 更多详见 https://router.vuejs.org/guide/advanced/meta.html
```tsx
routes: [
{
path: '/',
component: 'index',
meta: {
hello: 2
},
props: {
xx: 2
}
}
]
```
> feat(renderer-vue): vue router support extra params

- packages/preset-umi/src/commands/preview.ts
修复 `umi preview` 访问不到页面的问题，应该先过静态资源中间件再 fallback 。
> fix(preview): fallback order should after static resources

- jest.config.ts
配置 jest transform 忽略  compiled code，不然本地执行 单测巨卡 巨慢
下面 400s 都没开始执行用例
```bash
$time npm t
> test
> jest
RUNS  packages/bundler-webpack/src/build.test.ts
RUNS  packages/bundler-vite/src/build.test.ts
RUNS  packages/bundler-esbuild/src/build.test.ts
RUNS  packages/plugin-docs/src/compiler.test.ts
RUNS  packages/babel-preset-umi/src/index.test.ts
RUNS  packages/mfsu/src/babelPlugins/awaitImport/awaitImport.test.ts
RUNS  packages/preset-umi/src/commands/generators/page.test.ts
Test Suites: 0 of 61 total
Tests:       0 total
Snapshots:   0 total
Time:        400 s
```
> test: ✅ jest config ignore compiled code

- docs/docs/api/api.md
- packages/renderer-react/src/index.ts
导出 react-router@6 的 `resolvePath` 函数，便于 runtime 对 path 做 join 操作，比如 reduce matchRoutes 拿到当前 route 的 full path
> refactor(renderer-react): export resolvePath util

- examples/ant-design-pro/package.json
- examples/ant-design-pro/src/app.tsx
- packages/plugins/src/layout.ts
- pnpm-lock.yaml
如果package.json 中有 techui 或者pro-layout，会找到用户的。两者中优先使用techui
```
/**
* 优先去找 '@alipay/tech-ui'，保证稳定性
*/
const depList = ['@alipay/tech-ui', '@ant-design/pro-layout'];
const pkgHasDep = depList.find((dep) => {
const { pkg } = api;
if (pkg.dependencies?.[dep] || pkg.devDependencies?.[dep]) {
return true;
}
return false;
});
const getPkgPath = () => {
// 如果  layout 和 techui至少有一个在，找到他们的地址
if (
pkgHasDep &&
existsSync(join(api.cwd, 'node_modules', pkgHasDep, 'package.json'))
) {
return join(api.cwd, 'node_modules', pkgHasDep);
}
// 如果项目中没有去找插件以来的
return dirname(require.resolve('@ant-design/pro-layout/package.json'));
};
```
> fix(plugin): layout use package.json version

- packages/preset-umi/src/features/configPlugins/configPlugins.ts
`targets` 不需要给 default 值，否则会被合并，不符合预期。
因为 `targets` 在 getConfig 的时候会判断是不是空值给予默认值了。
> fix(targets): not set default targets value

- packages/bundler-webpack/src/build.test.ts
- packages/bundler-webpack/src/fixtures/runtime-public-path/config.ts
- packages/bundler-webpack/src/fixtures/runtime-public-path/index.css
- packages/bundler-webpack/src/fixtures/runtime-public-path/index.ts
- packages/bundler-webpack/src/plugins/RuntimePublicPathPlugin.ts
开启 `runtimePublicPath` 之后 CSS 中引用 assets 资源的 `publicPath` 不是 `./` 而是 `/`
1、`umi g page index`
2、项目中新增一个超过 10K 的图片
3、在 css 中引用他
4、配置 `runtimePublicPath: {}`
5、执行 `COMPRESS=none umi build`
检查 `dist` 下的 `css` 文件，针对图片的引用，期望是通过 `./static/xxx` 的方式引入，而实际上是通过 `/static/xxx` 的方式引入。
原本 css 针对图片的引用是由 mini-css-extract 插件负责处理，但因为 runtimePublicPath 插件直接无条件将所有模块的 publicPath 都覆盖掉，导致问题发生。
在覆盖 publicPath 以前先判断该模块是否由 mini-css-extract 插件负责，如果是的话则不该动他的 publicPath 即可修复问题。
> fix(bundler-webpack): Fix runtimePublicPath effects assets url in css file

- packages/plugins/src/access.ts
Access 组件类型报错
```text
Type '{ children: Element; accessible: any; }' is not assignable to type 'IntrinsicAttributes & AccessProps'.
Property 'children' does not exist on type 'IntrinsicAttributes & AccessProps'.
(alias) const Access: React.FC<AccessProps>
import Access
```
原因  react18 类型定义移除了 `PropsWithChildren`，导致以上类型报错;  PR 中的改动在 React17 的环境下 会变成
`PropsWithChildren<PropsWithChildren<P>>` 等效于 `PropsWithChildren<P>`，可以兼容
```diff
interface FunctionComponent<P = {}> {
-       (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
+       (props: P, context?: any): ReactElement<any, any> | null;
```
> refactor: 🎨 better types for access component

- packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
修复运行时路由 patch 位置出错的 bug，#821 默认加了空的 `children`，已确定会改回去，但安全起见这里还是再判断下 `length`
> fix(plugins): runtime routes patch bug for qiankun

- packages/bundler-webpack/src/config/config.ts
表现
```bash
info  - Umi v4.0.0-canary.20220609.1
info  - Memory Usage: 1469.73 MB (RSS: 1633.73 MB)
fatal - Error: Conflict: Multiple chunks emit assets to the same filename 13.js (chunks 201 and 13)
at /Users/git/problem/bigtest/node_modules/_@umijs_bundler-webpack@4.0.0-canary.20220609.1@@umijs/bundler-webpack/compiled/webpack/index.js:60625:12
at /Users/git/problem/bigtest/node_modules/_@umijs_bundler-webpack@4.0.0-canary.20220609.1@@umijs/bundler-webpack/compiled/webpack/index.js:51251:5
```
路由组件的 chunkname 为  `数字.js` ，编译生成的chunk 的 使用 `[name].js` 和 路由组件冲突了。
> fix: 🐛 无 hash 配置下 使用 async 避免 chunkName 冲突

- packages/plugin-docs/client/theme-doc/ThemeSwitch.tsx
- packages/plugin-docs/client/theme-doc/tailwind.css
使用 color-scheme CSS 属性改进深色模式默认样式。
> feat(plugin-docs): Add color-scheme support

- package.json
- packages/create-umi/src/cli.ts
- packages/mfsu/src/babelPlugins/awaitImport/checkMatch.ts
- packages/preset-umi/src/features/monorepo/redirect.ts
- packages/umi/src/cli/node.ts
- packages/utils/src/index.ts
- packages/utils/src/isLocalDev.ts
1. 新增判断是否在本地开发方法 `isLocalDev`
2. 抽离所有判断是否在本地的逻辑
3. 现在 mfsu 本地开发时不限制仓库名了
> chore: extract check local method

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
目前，umi 支持导入 json 文件，但是 tsconfig.json 中不存在 resolveJsonModule: true 配置，typescript 就认为找不到模块。编辑器会在导入 json 文件的地方，出现红色下划线，这会给用户造成困扰。
如图：
> fix(preset-umi): 取消typescript关于import json的错误的类型提示

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
fix #867
`typings.d.ts` 位置在 `.umi` 临时文件夹下，而不是在 umi source dir 下
> fix(tsconfig): typings file alias (resolve #867)

- packages/renderer-react/src/browser.tsx
修复访问不存在路由时页面报错：cannot read properties of undefined(reading 'clientLoader')
> fix(renderer-react): clientLoader option access bug

- packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
tsconfig 新增了3个配置
- `importsNotUsedAsValues` 
解 webpack5 不支持 `import { IHello } from './types' `形式访问类型声明 需要写成 `import type { IHello} from './types'` 的形式
**Vue 框架新增两个配置**
- `isolatedModules`
vite 推荐的配置 https://vitejs.dev/guide/features.html#typescript 这里先写成了仅vue 支持
- `preserveValueImports`
For `<script setup>`
See <https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#preserve-value-imports>
> feat(preset-umi): tmpFiles tsconfig add config

- packages/plugins/src/layout.ts
当项目中 react 为 16 版本时，开启layout后，报错”React is not defined“。
仓库中 max demo react 为 18 无这个问题
> fix: react is no defined when react16

- docs/docs/tutorials/getting-started.md
fix:docs/tutorials/getting-started 文档中 localhost:8000 后面会被当成url一部分
> fix:error in getting-start
